// Code generated by ent, DO NOT EDIT.

package contentinteraction

import (
	"silan-backend/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContainsFold(FieldID, id))
}

// EntityID applies equality check predicate on the "entity_id" field. It's identical to EntityIDEQ.
func EntityID(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldEntityID, v))
}

// SectionAnchor applies equality check predicate on the "section_anchor" field. It's identical to SectionAnchorEQ.
func SectionAnchor(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldSectionAnchor, v))
}

// UserIdentityID applies equality check predicate on the "user_identity_id" field. It's identical to UserIdentityIDEQ.
func UserIdentityID(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldUserIdentityID, v))
}

// Fingerprint applies equality check predicate on the "fingerprint" field. It's identical to FingerprintEQ.
func Fingerprint(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldFingerprint, v))
}

// IPAddress applies equality check predicate on the "ip_address" field. It's identical to IPAddressEQ.
func IPAddress(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldIPAddress, v))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldUserAgent, v))
}

// Referrer applies equality check predicate on the "referrer" field. It's identical to ReferrerEQ.
func Referrer(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldReferrer, v))
}

// LandingURL applies equality check predicate on the "landing_url" field. It's identical to LandingURLEQ.
func LandingURL(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldLandingURL, v))
}

// CrawlerName applies equality check predicate on the "crawler_name" field. It's identical to CrawlerNameEQ.
func CrawlerName(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldCrawlerName, v))
}

// CountryCode applies equality check predicate on the "country_code" field. It's identical to CountryCodeEQ.
func CountryCode(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldCountryCode, v))
}

// RegionCode applies equality check predicate on the "region_code" field. It's identical to RegionCodeEQ.
func RegionCode(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldRegionCode, v))
}

// RegionName applies equality check predicate on the "region_name" field. It's identical to RegionNameEQ.
func RegionName(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldRegionName, v))
}

// City applies equality check predicate on the "city" field. It's identical to CityEQ.
func City(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldCity, v))
}

// PostalCode applies equality check predicate on the "postal_code" field. It's identical to PostalCodeEQ.
func PostalCode(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldPostalCode, v))
}

// PlaceName applies equality check predicate on the "place_name" field. It's identical to PlaceNameEQ.
func PlaceName(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldPlaceName, v))
}

// PlaceFeatureCode applies equality check predicate on the "place_feature_code" field. It's identical to PlaceFeatureCodeEQ.
func PlaceFeatureCode(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldPlaceFeatureCode, v))
}

// PlaceDistanceKm applies equality check predicate on the "place_distance_km" field. It's identical to PlaceDistanceKmEQ.
func PlaceDistanceKm(v float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldPlaceDistanceKm, v))
}

// Latitude applies equality check predicate on the "latitude" field. It's identical to LatitudeEQ.
func Latitude(v float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldLatitude, v))
}

// Longitude applies equality check predicate on the "longitude" field. It's identical to LongitudeEQ.
func Longitude(v float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldLongitude, v))
}

// TimeZone applies equality check predicate on the "time_zone" field. It's identical to TimeZoneEQ.
func TimeZone(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldTimeZone, v))
}

// AccuracyRadius applies equality check predicate on the "accuracy_radius" field. It's identical to AccuracyRadiusEQ.
func AccuracyRadius(v int) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldAccuracyRadius, v))
}

// SessionDuration applies equality check predicate on the "session_duration" field. It's identical to SessionDurationEQ.
func SessionDuration(v int) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldSessionDuration, v))
}

// ScrollProgress applies equality check predicate on the "scroll_progress" field. It's identical to ScrollProgressEQ.
func ScrollProgress(v float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldScrollProgress, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldCreatedAt, v))
}

// EntityTypeEQ applies the EQ predicate on the "entity_type" field.
func EntityTypeEQ(v EntityType) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldEntityType, v))
}

// EntityTypeNEQ applies the NEQ predicate on the "entity_type" field.
func EntityTypeNEQ(v EntityType) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNEQ(FieldEntityType, v))
}

// EntityTypeIn applies the In predicate on the "entity_type" field.
func EntityTypeIn(vs ...EntityType) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIn(FieldEntityType, vs...))
}

// EntityTypeNotIn applies the NotIn predicate on the "entity_type" field.
func EntityTypeNotIn(vs ...EntityType) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotIn(FieldEntityType, vs...))
}

// EntityIDEQ applies the EQ predicate on the "entity_id" field.
func EntityIDEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldEntityID, v))
}

// EntityIDNEQ applies the NEQ predicate on the "entity_id" field.
func EntityIDNEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNEQ(FieldEntityID, v))
}

// EntityIDIn applies the In predicate on the "entity_id" field.
func EntityIDIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIn(FieldEntityID, vs...))
}

// EntityIDNotIn applies the NotIn predicate on the "entity_id" field.
func EntityIDNotIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotIn(FieldEntityID, vs...))
}

// EntityIDGT applies the GT predicate on the "entity_id" field.
func EntityIDGT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGT(FieldEntityID, v))
}

// EntityIDGTE applies the GTE predicate on the "entity_id" field.
func EntityIDGTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGTE(FieldEntityID, v))
}

// EntityIDLT applies the LT predicate on the "entity_id" field.
func EntityIDLT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLT(FieldEntityID, v))
}

// EntityIDLTE applies the LTE predicate on the "entity_id" field.
func EntityIDLTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLTE(FieldEntityID, v))
}

// EntityIDContains applies the Contains predicate on the "entity_id" field.
func EntityIDContains(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContains(FieldEntityID, v))
}

// EntityIDHasPrefix applies the HasPrefix predicate on the "entity_id" field.
func EntityIDHasPrefix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasPrefix(FieldEntityID, v))
}

// EntityIDHasSuffix applies the HasSuffix predicate on the "entity_id" field.
func EntityIDHasSuffix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasSuffix(FieldEntityID, v))
}

// EntityIDEqualFold applies the EqualFold predicate on the "entity_id" field.
func EntityIDEqualFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEqualFold(FieldEntityID, v))
}

// EntityIDContainsFold applies the ContainsFold predicate on the "entity_id" field.
func EntityIDContainsFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContainsFold(FieldEntityID, v))
}

// SectionAnchorEQ applies the EQ predicate on the "section_anchor" field.
func SectionAnchorEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldSectionAnchor, v))
}

// SectionAnchorNEQ applies the NEQ predicate on the "section_anchor" field.
func SectionAnchorNEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNEQ(FieldSectionAnchor, v))
}

// SectionAnchorIn applies the In predicate on the "section_anchor" field.
func SectionAnchorIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIn(FieldSectionAnchor, vs...))
}

// SectionAnchorNotIn applies the NotIn predicate on the "section_anchor" field.
func SectionAnchorNotIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotIn(FieldSectionAnchor, vs...))
}

// SectionAnchorGT applies the GT predicate on the "section_anchor" field.
func SectionAnchorGT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGT(FieldSectionAnchor, v))
}

// SectionAnchorGTE applies the GTE predicate on the "section_anchor" field.
func SectionAnchorGTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGTE(FieldSectionAnchor, v))
}

// SectionAnchorLT applies the LT predicate on the "section_anchor" field.
func SectionAnchorLT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLT(FieldSectionAnchor, v))
}

// SectionAnchorLTE applies the LTE predicate on the "section_anchor" field.
func SectionAnchorLTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLTE(FieldSectionAnchor, v))
}

// SectionAnchorContains applies the Contains predicate on the "section_anchor" field.
func SectionAnchorContains(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContains(FieldSectionAnchor, v))
}

// SectionAnchorHasPrefix applies the HasPrefix predicate on the "section_anchor" field.
func SectionAnchorHasPrefix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasPrefix(FieldSectionAnchor, v))
}

// SectionAnchorHasSuffix applies the HasSuffix predicate on the "section_anchor" field.
func SectionAnchorHasSuffix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasSuffix(FieldSectionAnchor, v))
}

// SectionAnchorIsNil applies the IsNil predicate on the "section_anchor" field.
func SectionAnchorIsNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIsNull(FieldSectionAnchor))
}

// SectionAnchorNotNil applies the NotNil predicate on the "section_anchor" field.
func SectionAnchorNotNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotNull(FieldSectionAnchor))
}

// SectionAnchorEqualFold applies the EqualFold predicate on the "section_anchor" field.
func SectionAnchorEqualFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEqualFold(FieldSectionAnchor, v))
}

// SectionAnchorContainsFold applies the ContainsFold predicate on the "section_anchor" field.
func SectionAnchorContainsFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContainsFold(FieldSectionAnchor, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v Kind) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v Kind) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...Kind) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...Kind) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotIn(FieldKind, vs...))
}

// UserIdentityIDEQ applies the EQ predicate on the "user_identity_id" field.
func UserIdentityIDEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldUserIdentityID, v))
}

// UserIdentityIDNEQ applies the NEQ predicate on the "user_identity_id" field.
func UserIdentityIDNEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNEQ(FieldUserIdentityID, v))
}

// UserIdentityIDIn applies the In predicate on the "user_identity_id" field.
func UserIdentityIDIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIn(FieldUserIdentityID, vs...))
}

// UserIdentityIDNotIn applies the NotIn predicate on the "user_identity_id" field.
func UserIdentityIDNotIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotIn(FieldUserIdentityID, vs...))
}

// UserIdentityIDGT applies the GT predicate on the "user_identity_id" field.
func UserIdentityIDGT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGT(FieldUserIdentityID, v))
}

// UserIdentityIDGTE applies the GTE predicate on the "user_identity_id" field.
func UserIdentityIDGTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGTE(FieldUserIdentityID, v))
}

// UserIdentityIDLT applies the LT predicate on the "user_identity_id" field.
func UserIdentityIDLT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLT(FieldUserIdentityID, v))
}

// UserIdentityIDLTE applies the LTE predicate on the "user_identity_id" field.
func UserIdentityIDLTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLTE(FieldUserIdentityID, v))
}

// UserIdentityIDContains applies the Contains predicate on the "user_identity_id" field.
func UserIdentityIDContains(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContains(FieldUserIdentityID, v))
}

// UserIdentityIDHasPrefix applies the HasPrefix predicate on the "user_identity_id" field.
func UserIdentityIDHasPrefix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasPrefix(FieldUserIdentityID, v))
}

// UserIdentityIDHasSuffix applies the HasSuffix predicate on the "user_identity_id" field.
func UserIdentityIDHasSuffix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasSuffix(FieldUserIdentityID, v))
}

// UserIdentityIDIsNil applies the IsNil predicate on the "user_identity_id" field.
func UserIdentityIDIsNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIsNull(FieldUserIdentityID))
}

// UserIdentityIDNotNil applies the NotNil predicate on the "user_identity_id" field.
func UserIdentityIDNotNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotNull(FieldUserIdentityID))
}

// UserIdentityIDEqualFold applies the EqualFold predicate on the "user_identity_id" field.
func UserIdentityIDEqualFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEqualFold(FieldUserIdentityID, v))
}

// UserIdentityIDContainsFold applies the ContainsFold predicate on the "user_identity_id" field.
func UserIdentityIDContainsFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContainsFold(FieldUserIdentityID, v))
}

// FingerprintEQ applies the EQ predicate on the "fingerprint" field.
func FingerprintEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldFingerprint, v))
}

// FingerprintNEQ applies the NEQ predicate on the "fingerprint" field.
func FingerprintNEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNEQ(FieldFingerprint, v))
}

// FingerprintIn applies the In predicate on the "fingerprint" field.
func FingerprintIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIn(FieldFingerprint, vs...))
}

// FingerprintNotIn applies the NotIn predicate on the "fingerprint" field.
func FingerprintNotIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotIn(FieldFingerprint, vs...))
}

// FingerprintGT applies the GT predicate on the "fingerprint" field.
func FingerprintGT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGT(FieldFingerprint, v))
}

// FingerprintGTE applies the GTE predicate on the "fingerprint" field.
func FingerprintGTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGTE(FieldFingerprint, v))
}

// FingerprintLT applies the LT predicate on the "fingerprint" field.
func FingerprintLT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLT(FieldFingerprint, v))
}

// FingerprintLTE applies the LTE predicate on the "fingerprint" field.
func FingerprintLTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLTE(FieldFingerprint, v))
}

// FingerprintContains applies the Contains predicate on the "fingerprint" field.
func FingerprintContains(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContains(FieldFingerprint, v))
}

// FingerprintHasPrefix applies the HasPrefix predicate on the "fingerprint" field.
func FingerprintHasPrefix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasPrefix(FieldFingerprint, v))
}

// FingerprintHasSuffix applies the HasSuffix predicate on the "fingerprint" field.
func FingerprintHasSuffix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasSuffix(FieldFingerprint, v))
}

// FingerprintIsNil applies the IsNil predicate on the "fingerprint" field.
func FingerprintIsNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIsNull(FieldFingerprint))
}

// FingerprintNotNil applies the NotNil predicate on the "fingerprint" field.
func FingerprintNotNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotNull(FieldFingerprint))
}

// FingerprintEqualFold applies the EqualFold predicate on the "fingerprint" field.
func FingerprintEqualFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEqualFold(FieldFingerprint, v))
}

// FingerprintContainsFold applies the ContainsFold predicate on the "fingerprint" field.
func FingerprintContainsFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContainsFold(FieldFingerprint, v))
}

// IPAddressEQ applies the EQ predicate on the "ip_address" field.
func IPAddressEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldIPAddress, v))
}

// IPAddressNEQ applies the NEQ predicate on the "ip_address" field.
func IPAddressNEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNEQ(FieldIPAddress, v))
}

// IPAddressIn applies the In predicate on the "ip_address" field.
func IPAddressIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIn(FieldIPAddress, vs...))
}

// IPAddressNotIn applies the NotIn predicate on the "ip_address" field.
func IPAddressNotIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotIn(FieldIPAddress, vs...))
}

// IPAddressGT applies the GT predicate on the "ip_address" field.
func IPAddressGT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGT(FieldIPAddress, v))
}

// IPAddressGTE applies the GTE predicate on the "ip_address" field.
func IPAddressGTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGTE(FieldIPAddress, v))
}

// IPAddressLT applies the LT predicate on the "ip_address" field.
func IPAddressLT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLT(FieldIPAddress, v))
}

// IPAddressLTE applies the LTE predicate on the "ip_address" field.
func IPAddressLTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLTE(FieldIPAddress, v))
}

// IPAddressContains applies the Contains predicate on the "ip_address" field.
func IPAddressContains(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContains(FieldIPAddress, v))
}

// IPAddressHasPrefix applies the HasPrefix predicate on the "ip_address" field.
func IPAddressHasPrefix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasPrefix(FieldIPAddress, v))
}

// IPAddressHasSuffix applies the HasSuffix predicate on the "ip_address" field.
func IPAddressHasSuffix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasSuffix(FieldIPAddress, v))
}

// IPAddressIsNil applies the IsNil predicate on the "ip_address" field.
func IPAddressIsNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIsNull(FieldIPAddress))
}

// IPAddressNotNil applies the NotNil predicate on the "ip_address" field.
func IPAddressNotNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotNull(FieldIPAddress))
}

// IPAddressEqualFold applies the EqualFold predicate on the "ip_address" field.
func IPAddressEqualFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEqualFold(FieldIPAddress, v))
}

// IPAddressContainsFold applies the ContainsFold predicate on the "ip_address" field.
func IPAddressContainsFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContainsFold(FieldIPAddress, v))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentIsNil applies the IsNil predicate on the "user_agent" field.
func UserAgentIsNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIsNull(FieldUserAgent))
}

// UserAgentNotNil applies the NotNil predicate on the "user_agent" field.
func UserAgentNotNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotNull(FieldUserAgent))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContainsFold(FieldUserAgent, v))
}

// VisitorKindEQ applies the EQ predicate on the "visitor_kind" field.
func VisitorKindEQ(v VisitorKind) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldVisitorKind, v))
}

// VisitorKindNEQ applies the NEQ predicate on the "visitor_kind" field.
func VisitorKindNEQ(v VisitorKind) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNEQ(FieldVisitorKind, v))
}

// VisitorKindIn applies the In predicate on the "visitor_kind" field.
func VisitorKindIn(vs ...VisitorKind) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIn(FieldVisitorKind, vs...))
}

// VisitorKindNotIn applies the NotIn predicate on the "visitor_kind" field.
func VisitorKindNotIn(vs ...VisitorKind) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotIn(FieldVisitorKind, vs...))
}

// ReferrerKindEQ applies the EQ predicate on the "referrer_kind" field.
func ReferrerKindEQ(v ReferrerKind) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldReferrerKind, v))
}

// ReferrerKindNEQ applies the NEQ predicate on the "referrer_kind" field.
func ReferrerKindNEQ(v ReferrerKind) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNEQ(FieldReferrerKind, v))
}

// ReferrerKindIn applies the In predicate on the "referrer_kind" field.
func ReferrerKindIn(vs ...ReferrerKind) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIn(FieldReferrerKind, vs...))
}

// ReferrerKindNotIn applies the NotIn predicate on the "referrer_kind" field.
func ReferrerKindNotIn(vs ...ReferrerKind) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotIn(FieldReferrerKind, vs...))
}

// ReferrerEQ applies the EQ predicate on the "referrer" field.
func ReferrerEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldReferrer, v))
}

// ReferrerNEQ applies the NEQ predicate on the "referrer" field.
func ReferrerNEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNEQ(FieldReferrer, v))
}

// ReferrerIn applies the In predicate on the "referrer" field.
func ReferrerIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIn(FieldReferrer, vs...))
}

// ReferrerNotIn applies the NotIn predicate on the "referrer" field.
func ReferrerNotIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotIn(FieldReferrer, vs...))
}

// ReferrerGT applies the GT predicate on the "referrer" field.
func ReferrerGT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGT(FieldReferrer, v))
}

// ReferrerGTE applies the GTE predicate on the "referrer" field.
func ReferrerGTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGTE(FieldReferrer, v))
}

// ReferrerLT applies the LT predicate on the "referrer" field.
func ReferrerLT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLT(FieldReferrer, v))
}

// ReferrerLTE applies the LTE predicate on the "referrer" field.
func ReferrerLTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLTE(FieldReferrer, v))
}

// ReferrerContains applies the Contains predicate on the "referrer" field.
func ReferrerContains(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContains(FieldReferrer, v))
}

// ReferrerHasPrefix applies the HasPrefix predicate on the "referrer" field.
func ReferrerHasPrefix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasPrefix(FieldReferrer, v))
}

// ReferrerHasSuffix applies the HasSuffix predicate on the "referrer" field.
func ReferrerHasSuffix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasSuffix(FieldReferrer, v))
}

// ReferrerIsNil applies the IsNil predicate on the "referrer" field.
func ReferrerIsNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIsNull(FieldReferrer))
}

// ReferrerNotNil applies the NotNil predicate on the "referrer" field.
func ReferrerNotNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotNull(FieldReferrer))
}

// ReferrerEqualFold applies the EqualFold predicate on the "referrer" field.
func ReferrerEqualFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEqualFold(FieldReferrer, v))
}

// ReferrerContainsFold applies the ContainsFold predicate on the "referrer" field.
func ReferrerContainsFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContainsFold(FieldReferrer, v))
}

// LandingURLEQ applies the EQ predicate on the "landing_url" field.
func LandingURLEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldLandingURL, v))
}

// LandingURLNEQ applies the NEQ predicate on the "landing_url" field.
func LandingURLNEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNEQ(FieldLandingURL, v))
}

// LandingURLIn applies the In predicate on the "landing_url" field.
func LandingURLIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIn(FieldLandingURL, vs...))
}

// LandingURLNotIn applies the NotIn predicate on the "landing_url" field.
func LandingURLNotIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotIn(FieldLandingURL, vs...))
}

// LandingURLGT applies the GT predicate on the "landing_url" field.
func LandingURLGT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGT(FieldLandingURL, v))
}

// LandingURLGTE applies the GTE predicate on the "landing_url" field.
func LandingURLGTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGTE(FieldLandingURL, v))
}

// LandingURLLT applies the LT predicate on the "landing_url" field.
func LandingURLLT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLT(FieldLandingURL, v))
}

// LandingURLLTE applies the LTE predicate on the "landing_url" field.
func LandingURLLTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLTE(FieldLandingURL, v))
}

// LandingURLContains applies the Contains predicate on the "landing_url" field.
func LandingURLContains(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContains(FieldLandingURL, v))
}

// LandingURLHasPrefix applies the HasPrefix predicate on the "landing_url" field.
func LandingURLHasPrefix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasPrefix(FieldLandingURL, v))
}

// LandingURLHasSuffix applies the HasSuffix predicate on the "landing_url" field.
func LandingURLHasSuffix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasSuffix(FieldLandingURL, v))
}

// LandingURLIsNil applies the IsNil predicate on the "landing_url" field.
func LandingURLIsNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIsNull(FieldLandingURL))
}

// LandingURLNotNil applies the NotNil predicate on the "landing_url" field.
func LandingURLNotNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotNull(FieldLandingURL))
}

// LandingURLEqualFold applies the EqualFold predicate on the "landing_url" field.
func LandingURLEqualFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEqualFold(FieldLandingURL, v))
}

// LandingURLContainsFold applies the ContainsFold predicate on the "landing_url" field.
func LandingURLContainsFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContainsFold(FieldLandingURL, v))
}

// CrawlerNameEQ applies the EQ predicate on the "crawler_name" field.
func CrawlerNameEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldCrawlerName, v))
}

// CrawlerNameNEQ applies the NEQ predicate on the "crawler_name" field.
func CrawlerNameNEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNEQ(FieldCrawlerName, v))
}

// CrawlerNameIn applies the In predicate on the "crawler_name" field.
func CrawlerNameIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIn(FieldCrawlerName, vs...))
}

// CrawlerNameNotIn applies the NotIn predicate on the "crawler_name" field.
func CrawlerNameNotIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotIn(FieldCrawlerName, vs...))
}

// CrawlerNameGT applies the GT predicate on the "crawler_name" field.
func CrawlerNameGT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGT(FieldCrawlerName, v))
}

// CrawlerNameGTE applies the GTE predicate on the "crawler_name" field.
func CrawlerNameGTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGTE(FieldCrawlerName, v))
}

// CrawlerNameLT applies the LT predicate on the "crawler_name" field.
func CrawlerNameLT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLT(FieldCrawlerName, v))
}

// CrawlerNameLTE applies the LTE predicate on the "crawler_name" field.
func CrawlerNameLTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLTE(FieldCrawlerName, v))
}

// CrawlerNameContains applies the Contains predicate on the "crawler_name" field.
func CrawlerNameContains(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContains(FieldCrawlerName, v))
}

// CrawlerNameHasPrefix applies the HasPrefix predicate on the "crawler_name" field.
func CrawlerNameHasPrefix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasPrefix(FieldCrawlerName, v))
}

// CrawlerNameHasSuffix applies the HasSuffix predicate on the "crawler_name" field.
func CrawlerNameHasSuffix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasSuffix(FieldCrawlerName, v))
}

// CrawlerNameIsNil applies the IsNil predicate on the "crawler_name" field.
func CrawlerNameIsNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIsNull(FieldCrawlerName))
}

// CrawlerNameNotNil applies the NotNil predicate on the "crawler_name" field.
func CrawlerNameNotNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotNull(FieldCrawlerName))
}

// CrawlerNameEqualFold applies the EqualFold predicate on the "crawler_name" field.
func CrawlerNameEqualFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEqualFold(FieldCrawlerName, v))
}

// CrawlerNameContainsFold applies the ContainsFold predicate on the "crawler_name" field.
func CrawlerNameContainsFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContainsFold(FieldCrawlerName, v))
}

// CountryCodeEQ applies the EQ predicate on the "country_code" field.
func CountryCodeEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldCountryCode, v))
}

// CountryCodeNEQ applies the NEQ predicate on the "country_code" field.
func CountryCodeNEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNEQ(FieldCountryCode, v))
}

// CountryCodeIn applies the In predicate on the "country_code" field.
func CountryCodeIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIn(FieldCountryCode, vs...))
}

// CountryCodeNotIn applies the NotIn predicate on the "country_code" field.
func CountryCodeNotIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotIn(FieldCountryCode, vs...))
}

// CountryCodeGT applies the GT predicate on the "country_code" field.
func CountryCodeGT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGT(FieldCountryCode, v))
}

// CountryCodeGTE applies the GTE predicate on the "country_code" field.
func CountryCodeGTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGTE(FieldCountryCode, v))
}

// CountryCodeLT applies the LT predicate on the "country_code" field.
func CountryCodeLT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLT(FieldCountryCode, v))
}

// CountryCodeLTE applies the LTE predicate on the "country_code" field.
func CountryCodeLTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLTE(FieldCountryCode, v))
}

// CountryCodeContains applies the Contains predicate on the "country_code" field.
func CountryCodeContains(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContains(FieldCountryCode, v))
}

// CountryCodeHasPrefix applies the HasPrefix predicate on the "country_code" field.
func CountryCodeHasPrefix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasPrefix(FieldCountryCode, v))
}

// CountryCodeHasSuffix applies the HasSuffix predicate on the "country_code" field.
func CountryCodeHasSuffix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasSuffix(FieldCountryCode, v))
}

// CountryCodeIsNil applies the IsNil predicate on the "country_code" field.
func CountryCodeIsNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIsNull(FieldCountryCode))
}

// CountryCodeNotNil applies the NotNil predicate on the "country_code" field.
func CountryCodeNotNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotNull(FieldCountryCode))
}

// CountryCodeEqualFold applies the EqualFold predicate on the "country_code" field.
func CountryCodeEqualFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEqualFold(FieldCountryCode, v))
}

// CountryCodeContainsFold applies the ContainsFold predicate on the "country_code" field.
func CountryCodeContainsFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContainsFold(FieldCountryCode, v))
}

// RegionCodeEQ applies the EQ predicate on the "region_code" field.
func RegionCodeEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldRegionCode, v))
}

// RegionCodeNEQ applies the NEQ predicate on the "region_code" field.
func RegionCodeNEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNEQ(FieldRegionCode, v))
}

// RegionCodeIn applies the In predicate on the "region_code" field.
func RegionCodeIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIn(FieldRegionCode, vs...))
}

// RegionCodeNotIn applies the NotIn predicate on the "region_code" field.
func RegionCodeNotIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotIn(FieldRegionCode, vs...))
}

// RegionCodeGT applies the GT predicate on the "region_code" field.
func RegionCodeGT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGT(FieldRegionCode, v))
}

// RegionCodeGTE applies the GTE predicate on the "region_code" field.
func RegionCodeGTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGTE(FieldRegionCode, v))
}

// RegionCodeLT applies the LT predicate on the "region_code" field.
func RegionCodeLT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLT(FieldRegionCode, v))
}

// RegionCodeLTE applies the LTE predicate on the "region_code" field.
func RegionCodeLTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLTE(FieldRegionCode, v))
}

// RegionCodeContains applies the Contains predicate on the "region_code" field.
func RegionCodeContains(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContains(FieldRegionCode, v))
}

// RegionCodeHasPrefix applies the HasPrefix predicate on the "region_code" field.
func RegionCodeHasPrefix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasPrefix(FieldRegionCode, v))
}

// RegionCodeHasSuffix applies the HasSuffix predicate on the "region_code" field.
func RegionCodeHasSuffix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasSuffix(FieldRegionCode, v))
}

// RegionCodeIsNil applies the IsNil predicate on the "region_code" field.
func RegionCodeIsNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIsNull(FieldRegionCode))
}

// RegionCodeNotNil applies the NotNil predicate on the "region_code" field.
func RegionCodeNotNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotNull(FieldRegionCode))
}

// RegionCodeEqualFold applies the EqualFold predicate on the "region_code" field.
func RegionCodeEqualFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEqualFold(FieldRegionCode, v))
}

// RegionCodeContainsFold applies the ContainsFold predicate on the "region_code" field.
func RegionCodeContainsFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContainsFold(FieldRegionCode, v))
}

// RegionNameEQ applies the EQ predicate on the "region_name" field.
func RegionNameEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldRegionName, v))
}

// RegionNameNEQ applies the NEQ predicate on the "region_name" field.
func RegionNameNEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNEQ(FieldRegionName, v))
}

// RegionNameIn applies the In predicate on the "region_name" field.
func RegionNameIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIn(FieldRegionName, vs...))
}

// RegionNameNotIn applies the NotIn predicate on the "region_name" field.
func RegionNameNotIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotIn(FieldRegionName, vs...))
}

// RegionNameGT applies the GT predicate on the "region_name" field.
func RegionNameGT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGT(FieldRegionName, v))
}

// RegionNameGTE applies the GTE predicate on the "region_name" field.
func RegionNameGTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGTE(FieldRegionName, v))
}

// RegionNameLT applies the LT predicate on the "region_name" field.
func RegionNameLT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLT(FieldRegionName, v))
}

// RegionNameLTE applies the LTE predicate on the "region_name" field.
func RegionNameLTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLTE(FieldRegionName, v))
}

// RegionNameContains applies the Contains predicate on the "region_name" field.
func RegionNameContains(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContains(FieldRegionName, v))
}

// RegionNameHasPrefix applies the HasPrefix predicate on the "region_name" field.
func RegionNameHasPrefix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasPrefix(FieldRegionName, v))
}

// RegionNameHasSuffix applies the HasSuffix predicate on the "region_name" field.
func RegionNameHasSuffix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasSuffix(FieldRegionName, v))
}

// RegionNameIsNil applies the IsNil predicate on the "region_name" field.
func RegionNameIsNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIsNull(FieldRegionName))
}

// RegionNameNotNil applies the NotNil predicate on the "region_name" field.
func RegionNameNotNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotNull(FieldRegionName))
}

// RegionNameEqualFold applies the EqualFold predicate on the "region_name" field.
func RegionNameEqualFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEqualFold(FieldRegionName, v))
}

// RegionNameContainsFold applies the ContainsFold predicate on the "region_name" field.
func RegionNameContainsFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContainsFold(FieldRegionName, v))
}

// CityEQ applies the EQ predicate on the "city" field.
func CityEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldCity, v))
}

// CityNEQ applies the NEQ predicate on the "city" field.
func CityNEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNEQ(FieldCity, v))
}

// CityIn applies the In predicate on the "city" field.
func CityIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIn(FieldCity, vs...))
}

// CityNotIn applies the NotIn predicate on the "city" field.
func CityNotIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotIn(FieldCity, vs...))
}

// CityGT applies the GT predicate on the "city" field.
func CityGT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGT(FieldCity, v))
}

// CityGTE applies the GTE predicate on the "city" field.
func CityGTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGTE(FieldCity, v))
}

// CityLT applies the LT predicate on the "city" field.
func CityLT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLT(FieldCity, v))
}

// CityLTE applies the LTE predicate on the "city" field.
func CityLTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLTE(FieldCity, v))
}

// CityContains applies the Contains predicate on the "city" field.
func CityContains(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContains(FieldCity, v))
}

// CityHasPrefix applies the HasPrefix predicate on the "city" field.
func CityHasPrefix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasPrefix(FieldCity, v))
}

// CityHasSuffix applies the HasSuffix predicate on the "city" field.
func CityHasSuffix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasSuffix(FieldCity, v))
}

// CityIsNil applies the IsNil predicate on the "city" field.
func CityIsNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIsNull(FieldCity))
}

// CityNotNil applies the NotNil predicate on the "city" field.
func CityNotNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotNull(FieldCity))
}

// CityEqualFold applies the EqualFold predicate on the "city" field.
func CityEqualFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEqualFold(FieldCity, v))
}

// CityContainsFold applies the ContainsFold predicate on the "city" field.
func CityContainsFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContainsFold(FieldCity, v))
}

// PostalCodeEQ applies the EQ predicate on the "postal_code" field.
func PostalCodeEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldPostalCode, v))
}

// PostalCodeNEQ applies the NEQ predicate on the "postal_code" field.
func PostalCodeNEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNEQ(FieldPostalCode, v))
}

// PostalCodeIn applies the In predicate on the "postal_code" field.
func PostalCodeIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIn(FieldPostalCode, vs...))
}

// PostalCodeNotIn applies the NotIn predicate on the "postal_code" field.
func PostalCodeNotIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotIn(FieldPostalCode, vs...))
}

// PostalCodeGT applies the GT predicate on the "postal_code" field.
func PostalCodeGT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGT(FieldPostalCode, v))
}

// PostalCodeGTE applies the GTE predicate on the "postal_code" field.
func PostalCodeGTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGTE(FieldPostalCode, v))
}

// PostalCodeLT applies the LT predicate on the "postal_code" field.
func PostalCodeLT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLT(FieldPostalCode, v))
}

// PostalCodeLTE applies the LTE predicate on the "postal_code" field.
func PostalCodeLTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLTE(FieldPostalCode, v))
}

// PostalCodeContains applies the Contains predicate on the "postal_code" field.
func PostalCodeContains(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContains(FieldPostalCode, v))
}

// PostalCodeHasPrefix applies the HasPrefix predicate on the "postal_code" field.
func PostalCodeHasPrefix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasPrefix(FieldPostalCode, v))
}

// PostalCodeHasSuffix applies the HasSuffix predicate on the "postal_code" field.
func PostalCodeHasSuffix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasSuffix(FieldPostalCode, v))
}

// PostalCodeIsNil applies the IsNil predicate on the "postal_code" field.
func PostalCodeIsNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIsNull(FieldPostalCode))
}

// PostalCodeNotNil applies the NotNil predicate on the "postal_code" field.
func PostalCodeNotNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotNull(FieldPostalCode))
}

// PostalCodeEqualFold applies the EqualFold predicate on the "postal_code" field.
func PostalCodeEqualFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEqualFold(FieldPostalCode, v))
}

// PostalCodeContainsFold applies the ContainsFold predicate on the "postal_code" field.
func PostalCodeContainsFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContainsFold(FieldPostalCode, v))
}

// PlaceNameEQ applies the EQ predicate on the "place_name" field.
func PlaceNameEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldPlaceName, v))
}

// PlaceNameNEQ applies the NEQ predicate on the "place_name" field.
func PlaceNameNEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNEQ(FieldPlaceName, v))
}

// PlaceNameIn applies the In predicate on the "place_name" field.
func PlaceNameIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIn(FieldPlaceName, vs...))
}

// PlaceNameNotIn applies the NotIn predicate on the "place_name" field.
func PlaceNameNotIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotIn(FieldPlaceName, vs...))
}

// PlaceNameGT applies the GT predicate on the "place_name" field.
func PlaceNameGT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGT(FieldPlaceName, v))
}

// PlaceNameGTE applies the GTE predicate on the "place_name" field.
func PlaceNameGTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGTE(FieldPlaceName, v))
}

// PlaceNameLT applies the LT predicate on the "place_name" field.
func PlaceNameLT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLT(FieldPlaceName, v))
}

// PlaceNameLTE applies the LTE predicate on the "place_name" field.
func PlaceNameLTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLTE(FieldPlaceName, v))
}

// PlaceNameContains applies the Contains predicate on the "place_name" field.
func PlaceNameContains(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContains(FieldPlaceName, v))
}

// PlaceNameHasPrefix applies the HasPrefix predicate on the "place_name" field.
func PlaceNameHasPrefix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasPrefix(FieldPlaceName, v))
}

// PlaceNameHasSuffix applies the HasSuffix predicate on the "place_name" field.
func PlaceNameHasSuffix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasSuffix(FieldPlaceName, v))
}

// PlaceNameIsNil applies the IsNil predicate on the "place_name" field.
func PlaceNameIsNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIsNull(FieldPlaceName))
}

// PlaceNameNotNil applies the NotNil predicate on the "place_name" field.
func PlaceNameNotNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotNull(FieldPlaceName))
}

// PlaceNameEqualFold applies the EqualFold predicate on the "place_name" field.
func PlaceNameEqualFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEqualFold(FieldPlaceName, v))
}

// PlaceNameContainsFold applies the ContainsFold predicate on the "place_name" field.
func PlaceNameContainsFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContainsFold(FieldPlaceName, v))
}

// PlaceFeatureCodeEQ applies the EQ predicate on the "place_feature_code" field.
func PlaceFeatureCodeEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldPlaceFeatureCode, v))
}

// PlaceFeatureCodeNEQ applies the NEQ predicate on the "place_feature_code" field.
func PlaceFeatureCodeNEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNEQ(FieldPlaceFeatureCode, v))
}

// PlaceFeatureCodeIn applies the In predicate on the "place_feature_code" field.
func PlaceFeatureCodeIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIn(FieldPlaceFeatureCode, vs...))
}

// PlaceFeatureCodeNotIn applies the NotIn predicate on the "place_feature_code" field.
func PlaceFeatureCodeNotIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotIn(FieldPlaceFeatureCode, vs...))
}

// PlaceFeatureCodeGT applies the GT predicate on the "place_feature_code" field.
func PlaceFeatureCodeGT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGT(FieldPlaceFeatureCode, v))
}

// PlaceFeatureCodeGTE applies the GTE predicate on the "place_feature_code" field.
func PlaceFeatureCodeGTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGTE(FieldPlaceFeatureCode, v))
}

// PlaceFeatureCodeLT applies the LT predicate on the "place_feature_code" field.
func PlaceFeatureCodeLT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLT(FieldPlaceFeatureCode, v))
}

// PlaceFeatureCodeLTE applies the LTE predicate on the "place_feature_code" field.
func PlaceFeatureCodeLTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLTE(FieldPlaceFeatureCode, v))
}

// PlaceFeatureCodeContains applies the Contains predicate on the "place_feature_code" field.
func PlaceFeatureCodeContains(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContains(FieldPlaceFeatureCode, v))
}

// PlaceFeatureCodeHasPrefix applies the HasPrefix predicate on the "place_feature_code" field.
func PlaceFeatureCodeHasPrefix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasPrefix(FieldPlaceFeatureCode, v))
}

// PlaceFeatureCodeHasSuffix applies the HasSuffix predicate on the "place_feature_code" field.
func PlaceFeatureCodeHasSuffix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasSuffix(FieldPlaceFeatureCode, v))
}

// PlaceFeatureCodeIsNil applies the IsNil predicate on the "place_feature_code" field.
func PlaceFeatureCodeIsNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIsNull(FieldPlaceFeatureCode))
}

// PlaceFeatureCodeNotNil applies the NotNil predicate on the "place_feature_code" field.
func PlaceFeatureCodeNotNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotNull(FieldPlaceFeatureCode))
}

// PlaceFeatureCodeEqualFold applies the EqualFold predicate on the "place_feature_code" field.
func PlaceFeatureCodeEqualFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEqualFold(FieldPlaceFeatureCode, v))
}

// PlaceFeatureCodeContainsFold applies the ContainsFold predicate on the "place_feature_code" field.
func PlaceFeatureCodeContainsFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContainsFold(FieldPlaceFeatureCode, v))
}

// PlaceDistanceKmEQ applies the EQ predicate on the "place_distance_km" field.
func PlaceDistanceKmEQ(v float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldPlaceDistanceKm, v))
}

// PlaceDistanceKmNEQ applies the NEQ predicate on the "place_distance_km" field.
func PlaceDistanceKmNEQ(v float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNEQ(FieldPlaceDistanceKm, v))
}

// PlaceDistanceKmIn applies the In predicate on the "place_distance_km" field.
func PlaceDistanceKmIn(vs ...float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIn(FieldPlaceDistanceKm, vs...))
}

// PlaceDistanceKmNotIn applies the NotIn predicate on the "place_distance_km" field.
func PlaceDistanceKmNotIn(vs ...float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotIn(FieldPlaceDistanceKm, vs...))
}

// PlaceDistanceKmGT applies the GT predicate on the "place_distance_km" field.
func PlaceDistanceKmGT(v float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGT(FieldPlaceDistanceKm, v))
}

// PlaceDistanceKmGTE applies the GTE predicate on the "place_distance_km" field.
func PlaceDistanceKmGTE(v float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGTE(FieldPlaceDistanceKm, v))
}

// PlaceDistanceKmLT applies the LT predicate on the "place_distance_km" field.
func PlaceDistanceKmLT(v float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLT(FieldPlaceDistanceKm, v))
}

// PlaceDistanceKmLTE applies the LTE predicate on the "place_distance_km" field.
func PlaceDistanceKmLTE(v float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLTE(FieldPlaceDistanceKm, v))
}

// PlaceDistanceKmIsNil applies the IsNil predicate on the "place_distance_km" field.
func PlaceDistanceKmIsNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIsNull(FieldPlaceDistanceKm))
}

// PlaceDistanceKmNotNil applies the NotNil predicate on the "place_distance_km" field.
func PlaceDistanceKmNotNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotNull(FieldPlaceDistanceKm))
}

// LatitudeEQ applies the EQ predicate on the "latitude" field.
func LatitudeEQ(v float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldLatitude, v))
}

// LatitudeNEQ applies the NEQ predicate on the "latitude" field.
func LatitudeNEQ(v float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNEQ(FieldLatitude, v))
}

// LatitudeIn applies the In predicate on the "latitude" field.
func LatitudeIn(vs ...float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIn(FieldLatitude, vs...))
}

// LatitudeNotIn applies the NotIn predicate on the "latitude" field.
func LatitudeNotIn(vs ...float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotIn(FieldLatitude, vs...))
}

// LatitudeGT applies the GT predicate on the "latitude" field.
func LatitudeGT(v float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGT(FieldLatitude, v))
}

// LatitudeGTE applies the GTE predicate on the "latitude" field.
func LatitudeGTE(v float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGTE(FieldLatitude, v))
}

// LatitudeLT applies the LT predicate on the "latitude" field.
func LatitudeLT(v float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLT(FieldLatitude, v))
}

// LatitudeLTE applies the LTE predicate on the "latitude" field.
func LatitudeLTE(v float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLTE(FieldLatitude, v))
}

// LatitudeIsNil applies the IsNil predicate on the "latitude" field.
func LatitudeIsNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIsNull(FieldLatitude))
}

// LatitudeNotNil applies the NotNil predicate on the "latitude" field.
func LatitudeNotNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotNull(FieldLatitude))
}

// LongitudeEQ applies the EQ predicate on the "longitude" field.
func LongitudeEQ(v float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldLongitude, v))
}

// LongitudeNEQ applies the NEQ predicate on the "longitude" field.
func LongitudeNEQ(v float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNEQ(FieldLongitude, v))
}

// LongitudeIn applies the In predicate on the "longitude" field.
func LongitudeIn(vs ...float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIn(FieldLongitude, vs...))
}

// LongitudeNotIn applies the NotIn predicate on the "longitude" field.
func LongitudeNotIn(vs ...float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotIn(FieldLongitude, vs...))
}

// LongitudeGT applies the GT predicate on the "longitude" field.
func LongitudeGT(v float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGT(FieldLongitude, v))
}

// LongitudeGTE applies the GTE predicate on the "longitude" field.
func LongitudeGTE(v float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGTE(FieldLongitude, v))
}

// LongitudeLT applies the LT predicate on the "longitude" field.
func LongitudeLT(v float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLT(FieldLongitude, v))
}

// LongitudeLTE applies the LTE predicate on the "longitude" field.
func LongitudeLTE(v float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLTE(FieldLongitude, v))
}

// LongitudeIsNil applies the IsNil predicate on the "longitude" field.
func LongitudeIsNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIsNull(FieldLongitude))
}

// LongitudeNotNil applies the NotNil predicate on the "longitude" field.
func LongitudeNotNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotNull(FieldLongitude))
}

// TimeZoneEQ applies the EQ predicate on the "time_zone" field.
func TimeZoneEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldTimeZone, v))
}

// TimeZoneNEQ applies the NEQ predicate on the "time_zone" field.
func TimeZoneNEQ(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNEQ(FieldTimeZone, v))
}

// TimeZoneIn applies the In predicate on the "time_zone" field.
func TimeZoneIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIn(FieldTimeZone, vs...))
}

// TimeZoneNotIn applies the NotIn predicate on the "time_zone" field.
func TimeZoneNotIn(vs ...string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotIn(FieldTimeZone, vs...))
}

// TimeZoneGT applies the GT predicate on the "time_zone" field.
func TimeZoneGT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGT(FieldTimeZone, v))
}

// TimeZoneGTE applies the GTE predicate on the "time_zone" field.
func TimeZoneGTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGTE(FieldTimeZone, v))
}

// TimeZoneLT applies the LT predicate on the "time_zone" field.
func TimeZoneLT(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLT(FieldTimeZone, v))
}

// TimeZoneLTE applies the LTE predicate on the "time_zone" field.
func TimeZoneLTE(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLTE(FieldTimeZone, v))
}

// TimeZoneContains applies the Contains predicate on the "time_zone" field.
func TimeZoneContains(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContains(FieldTimeZone, v))
}

// TimeZoneHasPrefix applies the HasPrefix predicate on the "time_zone" field.
func TimeZoneHasPrefix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasPrefix(FieldTimeZone, v))
}

// TimeZoneHasSuffix applies the HasSuffix predicate on the "time_zone" field.
func TimeZoneHasSuffix(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldHasSuffix(FieldTimeZone, v))
}

// TimeZoneIsNil applies the IsNil predicate on the "time_zone" field.
func TimeZoneIsNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIsNull(FieldTimeZone))
}

// TimeZoneNotNil applies the NotNil predicate on the "time_zone" field.
func TimeZoneNotNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotNull(FieldTimeZone))
}

// TimeZoneEqualFold applies the EqualFold predicate on the "time_zone" field.
func TimeZoneEqualFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEqualFold(FieldTimeZone, v))
}

// TimeZoneContainsFold applies the ContainsFold predicate on the "time_zone" field.
func TimeZoneContainsFold(v string) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldContainsFold(FieldTimeZone, v))
}

// AccuracyRadiusEQ applies the EQ predicate on the "accuracy_radius" field.
func AccuracyRadiusEQ(v int) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldAccuracyRadius, v))
}

// AccuracyRadiusNEQ applies the NEQ predicate on the "accuracy_radius" field.
func AccuracyRadiusNEQ(v int) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNEQ(FieldAccuracyRadius, v))
}

// AccuracyRadiusIn applies the In predicate on the "accuracy_radius" field.
func AccuracyRadiusIn(vs ...int) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIn(FieldAccuracyRadius, vs...))
}

// AccuracyRadiusNotIn applies the NotIn predicate on the "accuracy_radius" field.
func AccuracyRadiusNotIn(vs ...int) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotIn(FieldAccuracyRadius, vs...))
}

// AccuracyRadiusGT applies the GT predicate on the "accuracy_radius" field.
func AccuracyRadiusGT(v int) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGT(FieldAccuracyRadius, v))
}

// AccuracyRadiusGTE applies the GTE predicate on the "accuracy_radius" field.
func AccuracyRadiusGTE(v int) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGTE(FieldAccuracyRadius, v))
}

// AccuracyRadiusLT applies the LT predicate on the "accuracy_radius" field.
func AccuracyRadiusLT(v int) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLT(FieldAccuracyRadius, v))
}

// AccuracyRadiusLTE applies the LTE predicate on the "accuracy_radius" field.
func AccuracyRadiusLTE(v int) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLTE(FieldAccuracyRadius, v))
}

// AccuracyRadiusIsNil applies the IsNil predicate on the "accuracy_radius" field.
func AccuracyRadiusIsNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIsNull(FieldAccuracyRadius))
}

// AccuracyRadiusNotNil applies the NotNil predicate on the "accuracy_radius" field.
func AccuracyRadiusNotNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotNull(FieldAccuracyRadius))
}

// SessionDurationEQ applies the EQ predicate on the "session_duration" field.
func SessionDurationEQ(v int) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldSessionDuration, v))
}

// SessionDurationNEQ applies the NEQ predicate on the "session_duration" field.
func SessionDurationNEQ(v int) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNEQ(FieldSessionDuration, v))
}

// SessionDurationIn applies the In predicate on the "session_duration" field.
func SessionDurationIn(vs ...int) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIn(FieldSessionDuration, vs...))
}

// SessionDurationNotIn applies the NotIn predicate on the "session_duration" field.
func SessionDurationNotIn(vs ...int) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotIn(FieldSessionDuration, vs...))
}

// SessionDurationGT applies the GT predicate on the "session_duration" field.
func SessionDurationGT(v int) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGT(FieldSessionDuration, v))
}

// SessionDurationGTE applies the GTE predicate on the "session_duration" field.
func SessionDurationGTE(v int) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGTE(FieldSessionDuration, v))
}

// SessionDurationLT applies the LT predicate on the "session_duration" field.
func SessionDurationLT(v int) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLT(FieldSessionDuration, v))
}

// SessionDurationLTE applies the LTE predicate on the "session_duration" field.
func SessionDurationLTE(v int) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLTE(FieldSessionDuration, v))
}

// ScrollProgressEQ applies the EQ predicate on the "scroll_progress" field.
func ScrollProgressEQ(v float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldScrollProgress, v))
}

// ScrollProgressNEQ applies the NEQ predicate on the "scroll_progress" field.
func ScrollProgressNEQ(v float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNEQ(FieldScrollProgress, v))
}

// ScrollProgressIn applies the In predicate on the "scroll_progress" field.
func ScrollProgressIn(vs ...float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIn(FieldScrollProgress, vs...))
}

// ScrollProgressNotIn applies the NotIn predicate on the "scroll_progress" field.
func ScrollProgressNotIn(vs ...float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotIn(FieldScrollProgress, vs...))
}

// ScrollProgressGT applies the GT predicate on the "scroll_progress" field.
func ScrollProgressGT(v float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGT(FieldScrollProgress, v))
}

// ScrollProgressGTE applies the GTE predicate on the "scroll_progress" field.
func ScrollProgressGTE(v float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGTE(FieldScrollProgress, v))
}

// ScrollProgressLT applies the LT predicate on the "scroll_progress" field.
func ScrollProgressLT(v float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLT(FieldScrollProgress, v))
}

// ScrollProgressLTE applies the LTE predicate on the "scroll_progress" field.
func ScrollProgressLTE(v float64) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLTE(FieldScrollProgress, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.FieldNotNull(FieldCreatedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ContentInteraction) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ContentInteraction) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ContentInteraction) predicate.ContentInteraction {
	return predicate.ContentInteraction(sql.NotPredicates(p))
}
