// Code generated by ent, DO NOT EDIT.

package partentry

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the partentry type in the database.
	Label = "part_entry"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldItemPartID holds the string denoting the item_part_id field in the database.
	FieldItemPartID = "item_part_id"
	// FieldEntryID holds the string denoting the entry_id field in the database.
	FieldEntryID = "entry_id"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldSharedPayload holds the string denoting the shared_payload field in the database.
	FieldSharedPayload = "shared_payload"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeItemPart holds the string denoting the item_part edge name in mutations.
	EdgeItemPart = "item_part"
	// EdgeTranslations holds the string denoting the translations edge name in mutations.
	EdgeTranslations = "translations"
	// Table holds the table name of the partentry in the database.
	Table = "part_entry"
	// ItemPartTable is the table that holds the item_part relation/edge.
	ItemPartTable = "part_entry"
	// ItemPartInverseTable is the table name for the ItemPart entity.
	// It exists in this package in order to avoid circular dependency with the "itempart" package.
	ItemPartInverseTable = "item_part"
	// ItemPartColumn is the table column denoting the item_part relation/edge.
	ItemPartColumn = "item_part_id"
	// TranslationsTable is the table that holds the translations relation/edge.
	TranslationsTable = "part_entry_translation"
	// TranslationsInverseTable is the table name for the PartEntryTranslation entity.
	// It exists in this package in order to avoid circular dependency with the "partentrytranslation" package.
	TranslationsInverseTable = "part_entry_translation"
	// TranslationsColumn is the table column denoting the translations relation/edge.
	TranslationsColumn = "part_entry_id"
)

// Columns holds all SQL columns for partentry fields.
var Columns = []string{
	FieldID,
	FieldItemPartID,
	FieldEntryID,
	FieldSortOrder,
	FieldSharedPayload,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the PartEntry queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByItemPartID orders the results by the item_part_id field.
func ByItemPartID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldItemPartID, opts...).ToFunc()
}

// ByEntryID orders the results by the entry_id field.
func ByEntryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntryID, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByItemPartField orders the results by item_part field.
func ByItemPartField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newItemPartStep(), sql.OrderByField(field, opts...))
	}
}

// ByTranslationsCount orders the results by translations count.
func ByTranslationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTranslationsStep(), opts...)
	}
}

// ByTranslations orders the results by translations terms.
func ByTranslations(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTranslationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newItemPartStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ItemPartInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ItemPartTable, ItemPartColumn),
	)
}
func newTranslationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TranslationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TranslationsTable, TranslationsColumn),
	)
}
