// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"silan-backend/internal/ent/contentinteraction"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ContentInteraction is the model entity for the ContentInteraction schema.
type ContentInteraction struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// EntityType holds the value of the "entity_type" field.
	EntityType contentinteraction.EntityType `json:"entity_type,omitempty"`
	// EntityID holds the value of the "entity_id" field.
	EntityID string `json:"entity_id,omitempty"`
	// SectionAnchor holds the value of the "section_anchor" field.
	SectionAnchor *string `json:"section_anchor,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind contentinteraction.Kind `json:"kind,omitempty"`
	// UserIdentityID holds the value of the "user_identity_id" field.
	UserIdentityID *string `json:"user_identity_id,omitempty"`
	// Fingerprint holds the value of the "fingerprint" field.
	Fingerprint *string `json:"fingerprint,omitempty"`
	// IPAddress holds the value of the "ip_address" field.
	IPAddress *string `json:"ip_address,omitempty"`
	// UserAgent holds the value of the "user_agent" field.
	UserAgent *string `json:"user_agent,omitempty"`
	// VisitorKind holds the value of the "visitor_kind" field.
	VisitorKind contentinteraction.VisitorKind `json:"visitor_kind,omitempty"`
	// ReferrerKind holds the value of the "referrer_kind" field.
	ReferrerKind contentinteraction.ReferrerKind `json:"referrer_kind,omitempty"`
	// Referrer holds the value of the "referrer" field.
	Referrer *string `json:"referrer,omitempty"`
	// LandingURL holds the value of the "landing_url" field.
	LandingURL *string `json:"landing_url,omitempty"`
	// CrawlerName holds the value of the "crawler_name" field.
	CrawlerName *string `json:"crawler_name,omitempty"`
	// CountryCode holds the value of the "country_code" field.
	CountryCode string `json:"country_code,omitempty"`
	// RegionCode holds the value of the "region_code" field.
	RegionCode string `json:"region_code,omitempty"`
	// RegionName holds the value of the "region_name" field.
	RegionName string `json:"region_name,omitempty"`
	// City holds the value of the "city" field.
	City string `json:"city,omitempty"`
	// PostalCode holds the value of the "postal_code" field.
	PostalCode string `json:"postal_code,omitempty"`
	// PlaceName holds the value of the "place_name" field.
	PlaceName string `json:"place_name,omitempty"`
	// PlaceFeatureCode holds the value of the "place_feature_code" field.
	PlaceFeatureCode string `json:"place_feature_code,omitempty"`
	// PlaceDistanceKm holds the value of the "place_distance_km" field.
	PlaceDistanceKm float64 `json:"place_distance_km,omitempty"`
	// Latitude holds the value of the "latitude" field.
	Latitude float64 `json:"latitude,omitempty"`
	// Longitude holds the value of the "longitude" field.
	Longitude float64 `json:"longitude,omitempty"`
	// TimeZone holds the value of the "time_zone" field.
	TimeZone string `json:"time_zone,omitempty"`
	// AccuracyRadius holds the value of the "accuracy_radius" field.
	AccuracyRadius int `json:"accuracy_radius,omitempty"`
	// SessionDuration holds the value of the "session_duration" field.
	SessionDuration int `json:"session_duration,omitempty"`
	// ScrollProgress holds the value of the "scroll_progress" field.
	ScrollProgress float64 `json:"scroll_progress,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ContentInteraction) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case contentinteraction.FieldPlaceDistanceKm, contentinteraction.FieldLatitude, contentinteraction.FieldLongitude, contentinteraction.FieldScrollProgress:
			values[i] = new(sql.NullFloat64)
		case contentinteraction.FieldAccuracyRadius, contentinteraction.FieldSessionDuration:
			values[i] = new(sql.NullInt64)
		case contentinteraction.FieldID, contentinteraction.FieldEntityType, contentinteraction.FieldEntityID, contentinteraction.FieldSectionAnchor, contentinteraction.FieldKind, contentinteraction.FieldUserIdentityID, contentinteraction.FieldFingerprint, contentinteraction.FieldIPAddress, contentinteraction.FieldUserAgent, contentinteraction.FieldVisitorKind, contentinteraction.FieldReferrerKind, contentinteraction.FieldReferrer, contentinteraction.FieldLandingURL, contentinteraction.FieldCrawlerName, contentinteraction.FieldCountryCode, contentinteraction.FieldRegionCode, contentinteraction.FieldRegionName, contentinteraction.FieldCity, contentinteraction.FieldPostalCode, contentinteraction.FieldPlaceName, contentinteraction.FieldPlaceFeatureCode, contentinteraction.FieldTimeZone:
			values[i] = new(sql.NullString)
		case contentinteraction.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ContentInteraction fields.
func (ci *ContentInteraction) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case contentinteraction.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				ci.ID = value.String
			}
		case contentinteraction.FieldEntityType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entity_type", values[i])
			} else if value.Valid {
				ci.EntityType = contentinteraction.EntityType(value.String)
			}
		case contentinteraction.FieldEntityID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entity_id", values[i])
			} else if value.Valid {
				ci.EntityID = value.String
			}
		case contentinteraction.FieldSectionAnchor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field section_anchor", values[i])
			} else if value.Valid {
				ci.SectionAnchor = new(string)
				*ci.SectionAnchor = value.String
			}
		case contentinteraction.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				ci.Kind = contentinteraction.Kind(value.String)
			}
		case contentinteraction.FieldUserIdentityID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_identity_id", values[i])
			} else if value.Valid {
				ci.UserIdentityID = new(string)
				*ci.UserIdentityID = value.String
			}
		case contentinteraction.FieldFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fingerprint", values[i])
			} else if value.Valid {
				ci.Fingerprint = new(string)
				*ci.Fingerprint = value.String
			}
		case contentinteraction.FieldIPAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip_address", values[i])
			} else if value.Valid {
				ci.IPAddress = new(string)
				*ci.IPAddress = value.String
			}
		case contentinteraction.FieldUserAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_agent", values[i])
			} else if value.Valid {
				ci.UserAgent = new(string)
				*ci.UserAgent = value.String
			}
		case contentinteraction.FieldVisitorKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field visitor_kind", values[i])
			} else if value.Valid {
				ci.VisitorKind = contentinteraction.VisitorKind(value.String)
			}
		case contentinteraction.FieldReferrerKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field referrer_kind", values[i])
			} else if value.Valid {
				ci.ReferrerKind = contentinteraction.ReferrerKind(value.String)
			}
		case contentinteraction.FieldReferrer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field referrer", values[i])
			} else if value.Valid {
				ci.Referrer = new(string)
				*ci.Referrer = value.String
			}
		case contentinteraction.FieldLandingURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field landing_url", values[i])
			} else if value.Valid {
				ci.LandingURL = new(string)
				*ci.LandingURL = value.String
			}
		case contentinteraction.FieldCrawlerName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field crawler_name", values[i])
			} else if value.Valid {
				ci.CrawlerName = new(string)
				*ci.CrawlerName = value.String
			}
		case contentinteraction.FieldCountryCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field country_code", values[i])
			} else if value.Valid {
				ci.CountryCode = value.String
			}
		case contentinteraction.FieldRegionCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field region_code", values[i])
			} else if value.Valid {
				ci.RegionCode = value.String
			}
		case contentinteraction.FieldRegionName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field region_name", values[i])
			} else if value.Valid {
				ci.RegionName = value.String
			}
		case contentinteraction.FieldCity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field city", values[i])
			} else if value.Valid {
				ci.City = value.String
			}
		case contentinteraction.FieldPostalCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field postal_code", values[i])
			} else if value.Valid {
				ci.PostalCode = value.String
			}
		case contentinteraction.FieldPlaceName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field place_name", values[i])
			} else if value.Valid {
				ci.PlaceName = value.String
			}
		case contentinteraction.FieldPlaceFeatureCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field place_feature_code", values[i])
			} else if value.Valid {
				ci.PlaceFeatureCode = value.String
			}
		case contentinteraction.FieldPlaceDistanceKm:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field place_distance_km", values[i])
			} else if value.Valid {
				ci.PlaceDistanceKm = value.Float64
			}
		case contentinteraction.FieldLatitude:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field latitude", values[i])
			} else if value.Valid {
				ci.Latitude = value.Float64
			}
		case contentinteraction.FieldLongitude:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field longitude", values[i])
			} else if value.Valid {
				ci.Longitude = value.Float64
			}
		case contentinteraction.FieldTimeZone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field time_zone", values[i])
			} else if value.Valid {
				ci.TimeZone = value.String
			}
		case contentinteraction.FieldAccuracyRadius:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field accuracy_radius", values[i])
			} else if value.Valid {
				ci.AccuracyRadius = int(value.Int64)
			}
		case contentinteraction.FieldSessionDuration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field session_duration", values[i])
			} else if value.Valid {
				ci.SessionDuration = int(value.Int64)
			}
		case contentinteraction.FieldScrollProgress:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field scroll_progress", values[i])
			} else if value.Valid {
				ci.ScrollProgress = value.Float64
			}
		case contentinteraction.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ci.CreatedAt = value.Time
			}
		default:
			ci.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ContentInteraction.
// This includes values selected through modifiers, order, etc.
func (ci *ContentInteraction) Value(name string) (ent.Value, error) {
	return ci.selectValues.Get(name)
}

// Update returns a builder for updating this ContentInteraction.
// Note that you need to call ContentInteraction.Unwrap() before calling this method if this ContentInteraction
// was returned from a transaction, and the transaction was committed or rolled back.
func (ci *ContentInteraction) Update() *ContentInteractionUpdateOne {
	return NewContentInteractionClient(ci.config).UpdateOne(ci)
}

// Unwrap unwraps the ContentInteraction entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ci *ContentInteraction) Unwrap() *ContentInteraction {
	_tx, ok := ci.config.driver.(*txDriver)
	if !ok {
		panic("ent: ContentInteraction is not a transactional entity")
	}
	ci.config.driver = _tx.drv
	return ci
}

// String implements the fmt.Stringer.
func (ci *ContentInteraction) String() string {
	var builder strings.Builder
	builder.WriteString("ContentInteraction(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ci.ID))
	builder.WriteString("entity_type=")
	builder.WriteString(fmt.Sprintf("%v", ci.EntityType))
	builder.WriteString(", ")
	builder.WriteString("entity_id=")
	builder.WriteString(ci.EntityID)
	builder.WriteString(", ")
	if v := ci.SectionAnchor; v != nil {
		builder.WriteString("section_anchor=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(fmt.Sprintf("%v", ci.Kind))
	builder.WriteString(", ")
	if v := ci.UserIdentityID; v != nil {
		builder.WriteString("user_identity_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := ci.Fingerprint; v != nil {
		builder.WriteString("fingerprint=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := ci.IPAddress; v != nil {
		builder.WriteString("ip_address=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := ci.UserAgent; v != nil {
		builder.WriteString("user_agent=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("visitor_kind=")
	builder.WriteString(fmt.Sprintf("%v", ci.VisitorKind))
	builder.WriteString(", ")
	builder.WriteString("referrer_kind=")
	builder.WriteString(fmt.Sprintf("%v", ci.ReferrerKind))
	builder.WriteString(", ")
	if v := ci.Referrer; v != nil {
		builder.WriteString("referrer=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := ci.LandingURL; v != nil {
		builder.WriteString("landing_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := ci.CrawlerName; v != nil {
		builder.WriteString("crawler_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("country_code=")
	builder.WriteString(ci.CountryCode)
	builder.WriteString(", ")
	builder.WriteString("region_code=")
	builder.WriteString(ci.RegionCode)
	builder.WriteString(", ")
	builder.WriteString("region_name=")
	builder.WriteString(ci.RegionName)
	builder.WriteString(", ")
	builder.WriteString("city=")
	builder.WriteString(ci.City)
	builder.WriteString(", ")
	builder.WriteString("postal_code=")
	builder.WriteString(ci.PostalCode)
	builder.WriteString(", ")
	builder.WriteString("place_name=")
	builder.WriteString(ci.PlaceName)
	builder.WriteString(", ")
	builder.WriteString("place_feature_code=")
	builder.WriteString(ci.PlaceFeatureCode)
	builder.WriteString(", ")
	builder.WriteString("place_distance_km=")
	builder.WriteString(fmt.Sprintf("%v", ci.PlaceDistanceKm))
	builder.WriteString(", ")
	builder.WriteString("latitude=")
	builder.WriteString(fmt.Sprintf("%v", ci.Latitude))
	builder.WriteString(", ")
	builder.WriteString("longitude=")
	builder.WriteString(fmt.Sprintf("%v", ci.Longitude))
	builder.WriteString(", ")
	builder.WriteString("time_zone=")
	builder.WriteString(ci.TimeZone)
	builder.WriteString(", ")
	builder.WriteString("accuracy_radius=")
	builder.WriteString(fmt.Sprintf("%v", ci.AccuracyRadius))
	builder.WriteString(", ")
	builder.WriteString("session_duration=")
	builder.WriteString(fmt.Sprintf("%v", ci.SessionDuration))
	builder.WriteString(", ")
	builder.WriteString("scroll_progress=")
	builder.WriteString(fmt.Sprintf("%v", ci.ScrollProgress))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ci.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ContentInteractions is a parsable slice of ContentInteraction.
type ContentInteractions []*ContentInteraction
