// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"silan-backend/internal/ent/contentrelation"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ContentRelation is the model entity for the ContentRelation schema.
type ContentRelation struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// FromType holds the value of the "from_type" field.
	FromType contentrelation.FromType `json:"from_type,omitempty"`
	// FromID holds the value of the "from_id" field.
	FromID string `json:"from_id,omitempty"`
	// ToType holds the value of the "to_type" field.
	ToType contentrelation.ToType `json:"to_type,omitempty"`
	// ToID holds the value of the "to_id" field.
	ToID string `json:"to_id,omitempty"`
	// RelationType holds the value of the "relation_type" field.
	RelationType contentrelation.RelationType `json:"relation_type,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ContentRelation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case contentrelation.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case contentrelation.FieldID, contentrelation.FieldFromType, contentrelation.FieldFromID, contentrelation.FieldToType, contentrelation.FieldToID, contentrelation.FieldRelationType:
			values[i] = new(sql.NullString)
		case contentrelation.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ContentRelation fields.
func (cr *ContentRelation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case contentrelation.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				cr.ID = value.String
			}
		case contentrelation.FieldFromType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field from_type", values[i])
			} else if value.Valid {
				cr.FromType = contentrelation.FromType(value.String)
			}
		case contentrelation.FieldFromID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field from_id", values[i])
			} else if value.Valid {
				cr.FromID = value.String
			}
		case contentrelation.FieldToType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field to_type", values[i])
			} else if value.Valid {
				cr.ToType = contentrelation.ToType(value.String)
			}
		case contentrelation.FieldToID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field to_id", values[i])
			} else if value.Valid {
				cr.ToID = value.String
			}
		case contentrelation.FieldRelationType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field relation_type", values[i])
			} else if value.Valid {
				cr.RelationType = contentrelation.RelationType(value.String)
			}
		case contentrelation.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				cr.SortOrder = int(value.Int64)
			}
		case contentrelation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				cr.CreatedAt = value.Time
			}
		default:
			cr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ContentRelation.
// This includes values selected through modifiers, order, etc.
func (cr *ContentRelation) Value(name string) (ent.Value, error) {
	return cr.selectValues.Get(name)
}

// Update returns a builder for updating this ContentRelation.
// Note that you need to call ContentRelation.Unwrap() before calling this method if this ContentRelation
// was returned from a transaction, and the transaction was committed or rolled back.
func (cr *ContentRelation) Update() *ContentRelationUpdateOne {
	return NewContentRelationClient(cr.config).UpdateOne(cr)
}

// Unwrap unwraps the ContentRelation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cr *ContentRelation) Unwrap() *ContentRelation {
	_tx, ok := cr.config.driver.(*txDriver)
	if !ok {
		panic("ent: ContentRelation is not a transactional entity")
	}
	cr.config.driver = _tx.drv
	return cr
}

// String implements the fmt.Stringer.
func (cr *ContentRelation) String() string {
	var builder strings.Builder
	builder.WriteString("ContentRelation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", cr.ID))
	builder.WriteString("from_type=")
	builder.WriteString(fmt.Sprintf("%v", cr.FromType))
	builder.WriteString(", ")
	builder.WriteString("from_id=")
	builder.WriteString(cr.FromID)
	builder.WriteString(", ")
	builder.WriteString("to_type=")
	builder.WriteString(fmt.Sprintf("%v", cr.ToType))
	builder.WriteString(", ")
	builder.WriteString("to_id=")
	builder.WriteString(cr.ToID)
	builder.WriteString(", ")
	builder.WriteString("relation_type=")
	builder.WriteString(fmt.Sprintf("%v", cr.RelationType))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", cr.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(cr.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ContentRelations is a parsable slice of ContentRelation.
type ContentRelations []*ContentRelation
