// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"silan-backend/internal/ent/episode"
	"silan-backend/internal/ent/episodetranslation"
	"silan-backend/internal/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EpisodeTranslationQuery is the builder for querying EpisodeTranslation entities.
type EpisodeTranslationQuery struct {
	config
	ctx         *QueryContext
	order       []episodetranslation.OrderOption
	inters      []Interceptor
	predicates  []predicate.EpisodeTranslation
	withEpisode *EpisodeQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EpisodeTranslationQuery builder.
func (etq *EpisodeTranslationQuery) Where(ps ...predicate.EpisodeTranslation) *EpisodeTranslationQuery {
	etq.predicates = append(etq.predicates, ps...)
	return etq
}

// Limit the number of records to be returned by this query.
func (etq *EpisodeTranslationQuery) Limit(limit int) *EpisodeTranslationQuery {
	etq.ctx.Limit = &limit
	return etq
}

// Offset to start from.
func (etq *EpisodeTranslationQuery) Offset(offset int) *EpisodeTranslationQuery {
	etq.ctx.Offset = &offset
	return etq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (etq *EpisodeTranslationQuery) Unique(unique bool) *EpisodeTranslationQuery {
	etq.ctx.Unique = &unique
	return etq
}

// Order specifies how the records should be ordered.
func (etq *EpisodeTranslationQuery) Order(o ...episodetranslation.OrderOption) *EpisodeTranslationQuery {
	etq.order = append(etq.order, o...)
	return etq
}

// QueryEpisode chains the current query on the "episode" edge.
func (etq *EpisodeTranslationQuery) QueryEpisode() *EpisodeQuery {
	query := (&EpisodeClient{config: etq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := etq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := etq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(episodetranslation.Table, episodetranslation.FieldID, selector),
			sqlgraph.To(episode.Table, episode.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, episodetranslation.EpisodeTable, episodetranslation.EpisodeColumn),
		)
		fromU = sqlgraph.SetNeighbors(etq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first EpisodeTranslation entity from the query.
// Returns a *NotFoundError when no EpisodeTranslation was found.
func (etq *EpisodeTranslationQuery) First(ctx context.Context) (*EpisodeTranslation, error) {
	nodes, err := etq.Limit(1).All(setContextOp(ctx, etq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{episodetranslation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (etq *EpisodeTranslationQuery) FirstX(ctx context.Context) *EpisodeTranslation {
	node, err := etq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EpisodeTranslation ID from the query.
// Returns a *NotFoundError when no EpisodeTranslation ID was found.
func (etq *EpisodeTranslationQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = etq.Limit(1).IDs(setContextOp(ctx, etq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{episodetranslation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (etq *EpisodeTranslationQuery) FirstIDX(ctx context.Context) string {
	id, err := etq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EpisodeTranslation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EpisodeTranslation entity is found.
// Returns a *NotFoundError when no EpisodeTranslation entities are found.
func (etq *EpisodeTranslationQuery) Only(ctx context.Context) (*EpisodeTranslation, error) {
	nodes, err := etq.Limit(2).All(setContextOp(ctx, etq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{episodetranslation.Label}
	default:
		return nil, &NotSingularError{episodetranslation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (etq *EpisodeTranslationQuery) OnlyX(ctx context.Context) *EpisodeTranslation {
	node, err := etq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EpisodeTranslation ID in the query.
// Returns a *NotSingularError when more than one EpisodeTranslation ID is found.
// Returns a *NotFoundError when no entities are found.
func (etq *EpisodeTranslationQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = etq.Limit(2).IDs(setContextOp(ctx, etq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{episodetranslation.Label}
	default:
		err = &NotSingularError{episodetranslation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (etq *EpisodeTranslationQuery) OnlyIDX(ctx context.Context) string {
	id, err := etq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EpisodeTranslations.
func (etq *EpisodeTranslationQuery) All(ctx context.Context) ([]*EpisodeTranslation, error) {
	ctx = setContextOp(ctx, etq.ctx, ent.OpQueryAll)
	if err := etq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EpisodeTranslation, *EpisodeTranslationQuery]()
	return withInterceptors[[]*EpisodeTranslation](ctx, etq, qr, etq.inters)
}

// AllX is like All, but panics if an error occurs.
func (etq *EpisodeTranslationQuery) AllX(ctx context.Context) []*EpisodeTranslation {
	nodes, err := etq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EpisodeTranslation IDs.
func (etq *EpisodeTranslationQuery) IDs(ctx context.Context) (ids []string, err error) {
	if etq.ctx.Unique == nil && etq.path != nil {
		etq.Unique(true)
	}
	ctx = setContextOp(ctx, etq.ctx, ent.OpQueryIDs)
	if err = etq.Select(episodetranslation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (etq *EpisodeTranslationQuery) IDsX(ctx context.Context) []string {
	ids, err := etq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (etq *EpisodeTranslationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, etq.ctx, ent.OpQueryCount)
	if err := etq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, etq, querierCount[*EpisodeTranslationQuery](), etq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (etq *EpisodeTranslationQuery) CountX(ctx context.Context) int {
	count, err := etq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (etq *EpisodeTranslationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, etq.ctx, ent.OpQueryExist)
	switch _, err := etq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (etq *EpisodeTranslationQuery) ExistX(ctx context.Context) bool {
	exist, err := etq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EpisodeTranslationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (etq *EpisodeTranslationQuery) Clone() *EpisodeTranslationQuery {
	if etq == nil {
		return nil
	}
	return &EpisodeTranslationQuery{
		config:      etq.config,
		ctx:         etq.ctx.Clone(),
		order:       append([]episodetranslation.OrderOption{}, etq.order...),
		inters:      append([]Interceptor{}, etq.inters...),
		predicates:  append([]predicate.EpisodeTranslation{}, etq.predicates...),
		withEpisode: etq.withEpisode.Clone(),
		// clone intermediate query.
		sql:  etq.sql.Clone(),
		path: etq.path,
	}
}

// WithEpisode tells the query-builder to eager-load the nodes that are connected to
// the "episode" edge. The optional arguments are used to configure the query builder of the edge.
func (etq *EpisodeTranslationQuery) WithEpisode(opts ...func(*EpisodeQuery)) *EpisodeTranslationQuery {
	query := (&EpisodeClient{config: etq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	etq.withEpisode = query
	return etq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		EpisodeID string `json:"episode_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EpisodeTranslation.Query().
//		GroupBy(episodetranslation.FieldEpisodeID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (etq *EpisodeTranslationQuery) GroupBy(field string, fields ...string) *EpisodeTranslationGroupBy {
	etq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EpisodeTranslationGroupBy{build: etq}
	grbuild.flds = &etq.ctx.Fields
	grbuild.label = episodetranslation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		EpisodeID string `json:"episode_id,omitempty"`
//	}
//
//	client.EpisodeTranslation.Query().
//		Select(episodetranslation.FieldEpisodeID).
//		Scan(ctx, &v)
func (etq *EpisodeTranslationQuery) Select(fields ...string) *EpisodeTranslationSelect {
	etq.ctx.Fields = append(etq.ctx.Fields, fields...)
	sbuild := &EpisodeTranslationSelect{EpisodeTranslationQuery: etq}
	sbuild.label = episodetranslation.Label
	sbuild.flds, sbuild.scan = &etq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EpisodeTranslationSelect configured with the given aggregations.
func (etq *EpisodeTranslationQuery) Aggregate(fns ...AggregateFunc) *EpisodeTranslationSelect {
	return etq.Select().Aggregate(fns...)
}

func (etq *EpisodeTranslationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range etq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, etq); err != nil {
				return err
			}
		}
	}
	for _, f := range etq.ctx.Fields {
		if !episodetranslation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if etq.path != nil {
		prev, err := etq.path(ctx)
		if err != nil {
			return err
		}
		etq.sql = prev
	}
	return nil
}

func (etq *EpisodeTranslationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EpisodeTranslation, error) {
	var (
		nodes       = []*EpisodeTranslation{}
		_spec       = etq.querySpec()
		loadedTypes = [1]bool{
			etq.withEpisode != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EpisodeTranslation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EpisodeTranslation{config: etq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, etq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := etq.withEpisode; query != nil {
		if err := etq.loadEpisode(ctx, query, nodes, nil,
			func(n *EpisodeTranslation, e *Episode) { n.Edges.Episode = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (etq *EpisodeTranslationQuery) loadEpisode(ctx context.Context, query *EpisodeQuery, nodes []*EpisodeTranslation, init func(*EpisodeTranslation), assign func(*EpisodeTranslation, *Episode)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*EpisodeTranslation)
	for i := range nodes {
		fk := nodes[i].EpisodeID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(episode.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "episode_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (etq *EpisodeTranslationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := etq.querySpec()
	_spec.Node.Columns = etq.ctx.Fields
	if len(etq.ctx.Fields) > 0 {
		_spec.Unique = etq.ctx.Unique != nil && *etq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, etq.driver, _spec)
}

func (etq *EpisodeTranslationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(episodetranslation.Table, episodetranslation.Columns, sqlgraph.NewFieldSpec(episodetranslation.FieldID, field.TypeString))
	_spec.From = etq.sql
	if unique := etq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if etq.path != nil {
		_spec.Unique = true
	}
	if fields := etq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, episodetranslation.FieldID)
		for i := range fields {
			if fields[i] != episodetranslation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if etq.withEpisode != nil {
			_spec.Node.AddColumnOnce(episodetranslation.FieldEpisodeID)
		}
	}
	if ps := etq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := etq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := etq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := etq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (etq *EpisodeTranslationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(etq.driver.Dialect())
	t1 := builder.Table(episodetranslation.Table)
	columns := etq.ctx.Fields
	if len(columns) == 0 {
		columns = episodetranslation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if etq.sql != nil {
		selector = etq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if etq.ctx.Unique != nil && *etq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range etq.predicates {
		p(selector)
	}
	for _, p := range etq.order {
		p(selector)
	}
	if offset := etq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := etq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EpisodeTranslationGroupBy is the group-by builder for EpisodeTranslation entities.
type EpisodeTranslationGroupBy struct {
	selector
	build *EpisodeTranslationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (etgb *EpisodeTranslationGroupBy) Aggregate(fns ...AggregateFunc) *EpisodeTranslationGroupBy {
	etgb.fns = append(etgb.fns, fns...)
	return etgb
}

// Scan applies the selector query and scans the result into the given value.
func (etgb *EpisodeTranslationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, etgb.build.ctx, ent.OpQueryGroupBy)
	if err := etgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EpisodeTranslationQuery, *EpisodeTranslationGroupBy](ctx, etgb.build, etgb, etgb.build.inters, v)
}

func (etgb *EpisodeTranslationGroupBy) sqlScan(ctx context.Context, root *EpisodeTranslationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(etgb.fns))
	for _, fn := range etgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*etgb.flds)+len(etgb.fns))
		for _, f := range *etgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*etgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := etgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EpisodeTranslationSelect is the builder for selecting fields of EpisodeTranslation entities.
type EpisodeTranslationSelect struct {
	*EpisodeTranslationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ets *EpisodeTranslationSelect) Aggregate(fns ...AggregateFunc) *EpisodeTranslationSelect {
	ets.fns = append(ets.fns, fns...)
	return ets
}

// Scan applies the selector query and scans the result into the given value.
func (ets *EpisodeTranslationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ets.ctx, ent.OpQuerySelect)
	if err := ets.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EpisodeTranslationQuery, *EpisodeTranslationSelect](ctx, ets.EpisodeTranslationQuery, ets, ets.inters, v)
}

func (ets *EpisodeTranslationSelect) sqlScan(ctx context.Context, root *EpisodeTranslationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ets.fns))
	for _, fn := range ets.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ets.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ets.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
