// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"silan-backend/internal/ent/episodetranslation"
	"silan-backend/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EpisodeTranslationDelete is the builder for deleting a EpisodeTranslation entity.
type EpisodeTranslationDelete struct {
	config
	hooks    []Hook
	mutation *EpisodeTranslationMutation
}

// Where appends a list predicates to the EpisodeTranslationDelete builder.
func (etd *EpisodeTranslationDelete) Where(ps ...predicate.EpisodeTranslation) *EpisodeTranslationDelete {
	etd.mutation.Where(ps...)
	return etd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (etd *EpisodeTranslationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, etd.sqlExec, etd.mutation, etd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (etd *EpisodeTranslationDelete) ExecX(ctx context.Context) int {
	n, err := etd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (etd *EpisodeTranslationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(episodetranslation.Table, sqlgraph.NewFieldSpec(episodetranslation.FieldID, field.TypeUUID))
	if ps := etd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, etd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	etd.mutation.done = true
	return affected, err
}

// EpisodeTranslationDeleteOne is the builder for deleting a single EpisodeTranslation entity.
type EpisodeTranslationDeleteOne struct {
	etd *EpisodeTranslationDelete
}

// Where appends a list predicates to the EpisodeTranslationDelete builder.
func (etdo *EpisodeTranslationDeleteOne) Where(ps ...predicate.EpisodeTranslation) *EpisodeTranslationDeleteOne {
	etdo.etd.mutation.Where(ps...)
	return etdo
}

// Exec executes the deletion query.
func (etdo *EpisodeTranslationDeleteOne) Exec(ctx context.Context) error {
	n, err := etdo.etd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{episodetranslation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (etdo *EpisodeTranslationDeleteOne) ExecX(ctx context.Context) {
	if err := etdo.Exec(ctx); err != nil {
		panic(err)
	}
}
