// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"silan-backend/internal/ent/idea"
	"silan-backend/internal/ent/ideadetail"
	"silan-backend/internal/ent/ideadetailtranslation"
	"silan-backend/internal/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// IdeaDetailQuery is the builder for querying IdeaDetail entities.
type IdeaDetailQuery struct {
	config
	ctx              *QueryContext
	order            []ideadetail.OrderOption
	inters           []Interceptor
	predicates       []predicate.IdeaDetail
	withIdea         *IdeaQuery
	withTranslations *IdeaDetailTranslationQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the IdeaDetailQuery builder.
func (idq *IdeaDetailQuery) Where(ps ...predicate.IdeaDetail) *IdeaDetailQuery {
	idq.predicates = append(idq.predicates, ps...)
	return idq
}

// Limit the number of records to be returned by this query.
func (idq *IdeaDetailQuery) Limit(limit int) *IdeaDetailQuery {
	idq.ctx.Limit = &limit
	return idq
}

// Offset to start from.
func (idq *IdeaDetailQuery) Offset(offset int) *IdeaDetailQuery {
	idq.ctx.Offset = &offset
	return idq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (idq *IdeaDetailQuery) Unique(unique bool) *IdeaDetailQuery {
	idq.ctx.Unique = &unique
	return idq
}

// Order specifies how the records should be ordered.
func (idq *IdeaDetailQuery) Order(o ...ideadetail.OrderOption) *IdeaDetailQuery {
	idq.order = append(idq.order, o...)
	return idq
}

// QueryIdea chains the current query on the "idea" edge.
func (idq *IdeaDetailQuery) QueryIdea() *IdeaQuery {
	query := (&IdeaClient{config: idq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := idq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := idq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(ideadetail.Table, ideadetail.FieldID, selector),
			sqlgraph.To(idea.Table, idea.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, ideadetail.IdeaTable, ideadetail.IdeaColumn),
		)
		fromU = sqlgraph.SetNeighbors(idq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTranslations chains the current query on the "translations" edge.
func (idq *IdeaDetailQuery) QueryTranslations() *IdeaDetailTranslationQuery {
	query := (&IdeaDetailTranslationClient{config: idq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := idq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := idq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(ideadetail.Table, ideadetail.FieldID, selector),
			sqlgraph.To(ideadetailtranslation.Table, ideadetailtranslation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ideadetail.TranslationsTable, ideadetail.TranslationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(idq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first IdeaDetail entity from the query.
// Returns a *NotFoundError when no IdeaDetail was found.
func (idq *IdeaDetailQuery) First(ctx context.Context) (*IdeaDetail, error) {
	nodes, err := idq.Limit(1).All(setContextOp(ctx, idq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{ideadetail.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (idq *IdeaDetailQuery) FirstX(ctx context.Context) *IdeaDetail {
	node, err := idq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first IdeaDetail ID from the query.
// Returns a *NotFoundError when no IdeaDetail ID was found.
func (idq *IdeaDetailQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = idq.Limit(1).IDs(setContextOp(ctx, idq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{ideadetail.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (idq *IdeaDetailQuery) FirstIDX(ctx context.Context) string {
	id, err := idq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single IdeaDetail entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one IdeaDetail entity is found.
// Returns a *NotFoundError when no IdeaDetail entities are found.
func (idq *IdeaDetailQuery) Only(ctx context.Context) (*IdeaDetail, error) {
	nodes, err := idq.Limit(2).All(setContextOp(ctx, idq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{ideadetail.Label}
	default:
		return nil, &NotSingularError{ideadetail.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (idq *IdeaDetailQuery) OnlyX(ctx context.Context) *IdeaDetail {
	node, err := idq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only IdeaDetail ID in the query.
// Returns a *NotSingularError when more than one IdeaDetail ID is found.
// Returns a *NotFoundError when no entities are found.
func (idq *IdeaDetailQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = idq.Limit(2).IDs(setContextOp(ctx, idq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{ideadetail.Label}
	default:
		err = &NotSingularError{ideadetail.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (idq *IdeaDetailQuery) OnlyIDX(ctx context.Context) string {
	id, err := idq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of IdeaDetails.
func (idq *IdeaDetailQuery) All(ctx context.Context) ([]*IdeaDetail, error) {
	ctx = setContextOp(ctx, idq.ctx, ent.OpQueryAll)
	if err := idq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*IdeaDetail, *IdeaDetailQuery]()
	return withInterceptors[[]*IdeaDetail](ctx, idq, qr, idq.inters)
}

// AllX is like All, but panics if an error occurs.
func (idq *IdeaDetailQuery) AllX(ctx context.Context) []*IdeaDetail {
	nodes, err := idq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of IdeaDetail IDs.
func (idq *IdeaDetailQuery) IDs(ctx context.Context) (ids []string, err error) {
	if idq.ctx.Unique == nil && idq.path != nil {
		idq.Unique(true)
	}
	ctx = setContextOp(ctx, idq.ctx, ent.OpQueryIDs)
	if err = idq.Select(ideadetail.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (idq *IdeaDetailQuery) IDsX(ctx context.Context) []string {
	ids, err := idq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (idq *IdeaDetailQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, idq.ctx, ent.OpQueryCount)
	if err := idq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, idq, querierCount[*IdeaDetailQuery](), idq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (idq *IdeaDetailQuery) CountX(ctx context.Context) int {
	count, err := idq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (idq *IdeaDetailQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, idq.ctx, ent.OpQueryExist)
	switch _, err := idq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (idq *IdeaDetailQuery) ExistX(ctx context.Context) bool {
	exist, err := idq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the IdeaDetailQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (idq *IdeaDetailQuery) Clone() *IdeaDetailQuery {
	if idq == nil {
		return nil
	}
	return &IdeaDetailQuery{
		config:           idq.config,
		ctx:              idq.ctx.Clone(),
		order:            append([]ideadetail.OrderOption{}, idq.order...),
		inters:           append([]Interceptor{}, idq.inters...),
		predicates:       append([]predicate.IdeaDetail{}, idq.predicates...),
		withIdea:         idq.withIdea.Clone(),
		withTranslations: idq.withTranslations.Clone(),
		// clone intermediate query.
		sql:  idq.sql.Clone(),
		path: idq.path,
	}
}

// WithIdea tells the query-builder to eager-load the nodes that are connected to
// the "idea" edge. The optional arguments are used to configure the query builder of the edge.
func (idq *IdeaDetailQuery) WithIdea(opts ...func(*IdeaQuery)) *IdeaDetailQuery {
	query := (&IdeaClient{config: idq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	idq.withIdea = query
	return idq
}

// WithTranslations tells the query-builder to eager-load the nodes that are connected to
// the "translations" edge. The optional arguments are used to configure the query builder of the edge.
func (idq *IdeaDetailQuery) WithTranslations(opts ...func(*IdeaDetailTranslationQuery)) *IdeaDetailQuery {
	query := (&IdeaDetailTranslationClient{config: idq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	idq.withTranslations = query
	return idq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		IdeaID string `json:"idea_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.IdeaDetail.Query().
//		GroupBy(ideadetail.FieldIdeaID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (idq *IdeaDetailQuery) GroupBy(field string, fields ...string) *IdeaDetailGroupBy {
	idq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &IdeaDetailGroupBy{build: idq}
	grbuild.flds = &idq.ctx.Fields
	grbuild.label = ideadetail.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		IdeaID string `json:"idea_id,omitempty"`
//	}
//
//	client.IdeaDetail.Query().
//		Select(ideadetail.FieldIdeaID).
//		Scan(ctx, &v)
func (idq *IdeaDetailQuery) Select(fields ...string) *IdeaDetailSelect {
	idq.ctx.Fields = append(idq.ctx.Fields, fields...)
	sbuild := &IdeaDetailSelect{IdeaDetailQuery: idq}
	sbuild.label = ideadetail.Label
	sbuild.flds, sbuild.scan = &idq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a IdeaDetailSelect configured with the given aggregations.
func (idq *IdeaDetailQuery) Aggregate(fns ...AggregateFunc) *IdeaDetailSelect {
	return idq.Select().Aggregate(fns...)
}

func (idq *IdeaDetailQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range idq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, idq); err != nil {
				return err
			}
		}
	}
	for _, f := range idq.ctx.Fields {
		if !ideadetail.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if idq.path != nil {
		prev, err := idq.path(ctx)
		if err != nil {
			return err
		}
		idq.sql = prev
	}
	return nil
}

func (idq *IdeaDetailQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*IdeaDetail, error) {
	var (
		nodes       = []*IdeaDetail{}
		_spec       = idq.querySpec()
		loadedTypes = [2]bool{
			idq.withIdea != nil,
			idq.withTranslations != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*IdeaDetail).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &IdeaDetail{config: idq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, idq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := idq.withIdea; query != nil {
		if err := idq.loadIdea(ctx, query, nodes, nil,
			func(n *IdeaDetail, e *Idea) { n.Edges.Idea = e }); err != nil {
			return nil, err
		}
	}
	if query := idq.withTranslations; query != nil {
		if err := idq.loadTranslations(ctx, query, nodes,
			func(n *IdeaDetail) { n.Edges.Translations = []*IdeaDetailTranslation{} },
			func(n *IdeaDetail, e *IdeaDetailTranslation) { n.Edges.Translations = append(n.Edges.Translations, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (idq *IdeaDetailQuery) loadIdea(ctx context.Context, query *IdeaQuery, nodes []*IdeaDetail, init func(*IdeaDetail), assign func(*IdeaDetail, *Idea)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*IdeaDetail)
	for i := range nodes {
		fk := nodes[i].IdeaID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(idea.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "idea_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (idq *IdeaDetailQuery) loadTranslations(ctx context.Context, query *IdeaDetailTranslationQuery, nodes []*IdeaDetail, init func(*IdeaDetail), assign func(*IdeaDetail, *IdeaDetailTranslation)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*IdeaDetail)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(ideadetailtranslation.FieldIdeaDetailID)
	}
	query.Where(predicate.IdeaDetailTranslation(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(ideadetail.TranslationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.IdeaDetailID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "idea_detail_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (idq *IdeaDetailQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := idq.querySpec()
	_spec.Node.Columns = idq.ctx.Fields
	if len(idq.ctx.Fields) > 0 {
		_spec.Unique = idq.ctx.Unique != nil && *idq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, idq.driver, _spec)
}

func (idq *IdeaDetailQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(ideadetail.Table, ideadetail.Columns, sqlgraph.NewFieldSpec(ideadetail.FieldID, field.TypeString))
	_spec.From = idq.sql
	if unique := idq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if idq.path != nil {
		_spec.Unique = true
	}
	if fields := idq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ideadetail.FieldID)
		for i := range fields {
			if fields[i] != ideadetail.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if idq.withIdea != nil {
			_spec.Node.AddColumnOnce(ideadetail.FieldIdeaID)
		}
	}
	if ps := idq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := idq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := idq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := idq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (idq *IdeaDetailQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(idq.driver.Dialect())
	t1 := builder.Table(ideadetail.Table)
	columns := idq.ctx.Fields
	if len(columns) == 0 {
		columns = ideadetail.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if idq.sql != nil {
		selector = idq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if idq.ctx.Unique != nil && *idq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range idq.predicates {
		p(selector)
	}
	for _, p := range idq.order {
		p(selector)
	}
	if offset := idq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := idq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// IdeaDetailGroupBy is the group-by builder for IdeaDetail entities.
type IdeaDetailGroupBy struct {
	selector
	build *IdeaDetailQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (idgb *IdeaDetailGroupBy) Aggregate(fns ...AggregateFunc) *IdeaDetailGroupBy {
	idgb.fns = append(idgb.fns, fns...)
	return idgb
}

// Scan applies the selector query and scans the result into the given value.
func (idgb *IdeaDetailGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, idgb.build.ctx, ent.OpQueryGroupBy)
	if err := idgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IdeaDetailQuery, *IdeaDetailGroupBy](ctx, idgb.build, idgb, idgb.build.inters, v)
}

func (idgb *IdeaDetailGroupBy) sqlScan(ctx context.Context, root *IdeaDetailQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(idgb.fns))
	for _, fn := range idgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*idgb.flds)+len(idgb.fns))
		for _, f := range *idgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*idgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := idgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// IdeaDetailSelect is the builder for selecting fields of IdeaDetail entities.
type IdeaDetailSelect struct {
	*IdeaDetailQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ids *IdeaDetailSelect) Aggregate(fns ...AggregateFunc) *IdeaDetailSelect {
	ids.fns = append(ids.fns, fns...)
	return ids
}

// Scan applies the selector query and scans the result into the given value.
func (ids *IdeaDetailSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ids.ctx, ent.OpQuerySelect)
	if err := ids.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IdeaDetailQuery, *IdeaDetailSelect](ctx, ids.IdeaDetailQuery, ids, ids.inters, v)
}

func (ids *IdeaDetailSelect) sqlScan(ctx context.Context, root *IdeaDetailQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ids.fns))
	for _, fn := range ids.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ids.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ids.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
