// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"silan-backend/internal/ent/itempart"
	"silan-backend/internal/ent/itemparttranslation"
	"silan-backend/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ItemPartTranslationUpdate is the builder for updating ItemPartTranslation entities.
type ItemPartTranslationUpdate struct {
	config
	hooks    []Hook
	mutation *ItemPartTranslationMutation
}

// Where appends a list predicates to the ItemPartTranslationUpdate builder.
func (iptu *ItemPartTranslationUpdate) Where(ps ...predicate.ItemPartTranslation) *ItemPartTranslationUpdate {
	iptu.mutation.Where(ps...)
	return iptu
}

// SetItemPartID sets the "item_part_id" field.
func (iptu *ItemPartTranslationUpdate) SetItemPartID(s string) *ItemPartTranslationUpdate {
	iptu.mutation.SetItemPartID(s)
	return iptu
}

// SetNillableItemPartID sets the "item_part_id" field if the given value is not nil.
func (iptu *ItemPartTranslationUpdate) SetNillableItemPartID(s *string) *ItemPartTranslationUpdate {
	if s != nil {
		iptu.SetItemPartID(*s)
	}
	return iptu
}

// SetLanguageCode sets the "language_code" field.
func (iptu *ItemPartTranslationUpdate) SetLanguageCode(s string) *ItemPartTranslationUpdate {
	iptu.mutation.SetLanguageCode(s)
	return iptu
}

// SetNillableLanguageCode sets the "language_code" field if the given value is not nil.
func (iptu *ItemPartTranslationUpdate) SetNillableLanguageCode(s *string) *ItemPartTranslationUpdate {
	if s != nil {
		iptu.SetLanguageCode(*s)
	}
	return iptu
}

// SetBody sets the "body" field.
func (iptu *ItemPartTranslationUpdate) SetBody(s string) *ItemPartTranslationUpdate {
	iptu.mutation.SetBody(s)
	return iptu
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (iptu *ItemPartTranslationUpdate) SetNillableBody(s *string) *ItemPartTranslationUpdate {
	if s != nil {
		iptu.SetBody(*s)
	}
	return iptu
}

// SetItemPart sets the "item_part" edge to the ItemPart entity.
func (iptu *ItemPartTranslationUpdate) SetItemPart(i *ItemPart) *ItemPartTranslationUpdate {
	return iptu.SetItemPartID(i.ID)
}

// Mutation returns the ItemPartTranslationMutation object of the builder.
func (iptu *ItemPartTranslationUpdate) Mutation() *ItemPartTranslationMutation {
	return iptu.mutation
}

// ClearItemPart clears the "item_part" edge to the ItemPart entity.
func (iptu *ItemPartTranslationUpdate) ClearItemPart() *ItemPartTranslationUpdate {
	iptu.mutation.ClearItemPart()
	return iptu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (iptu *ItemPartTranslationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, iptu.sqlSave, iptu.mutation, iptu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iptu *ItemPartTranslationUpdate) SaveX(ctx context.Context) int {
	affected, err := iptu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (iptu *ItemPartTranslationUpdate) Exec(ctx context.Context) error {
	_, err := iptu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iptu *ItemPartTranslationUpdate) ExecX(ctx context.Context) {
	if err := iptu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iptu *ItemPartTranslationUpdate) check() error {
	if iptu.mutation.ItemPartCleared() && len(iptu.mutation.ItemPartIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ItemPartTranslation.item_part"`)
	}
	return nil
}

func (iptu *ItemPartTranslationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := iptu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(itemparttranslation.Table, itemparttranslation.Columns, sqlgraph.NewFieldSpec(itemparttranslation.FieldID, field.TypeString))
	if ps := iptu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iptu.mutation.LanguageCode(); ok {
		_spec.SetField(itemparttranslation.FieldLanguageCode, field.TypeString, value)
	}
	if value, ok := iptu.mutation.Body(); ok {
		_spec.SetField(itemparttranslation.FieldBody, field.TypeString, value)
	}
	if iptu.mutation.ItemPartCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemparttranslation.ItemPartTable,
			Columns: []string{itemparttranslation.ItemPartColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(itempart.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iptu.mutation.ItemPartIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemparttranslation.ItemPartTable,
			Columns: []string{itemparttranslation.ItemPartColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(itempart.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, iptu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{itemparttranslation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	iptu.mutation.done = true
	return n, nil
}

// ItemPartTranslationUpdateOne is the builder for updating a single ItemPartTranslation entity.
type ItemPartTranslationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ItemPartTranslationMutation
}

// SetItemPartID sets the "item_part_id" field.
func (iptuo *ItemPartTranslationUpdateOne) SetItemPartID(s string) *ItemPartTranslationUpdateOne {
	iptuo.mutation.SetItemPartID(s)
	return iptuo
}

// SetNillableItemPartID sets the "item_part_id" field if the given value is not nil.
func (iptuo *ItemPartTranslationUpdateOne) SetNillableItemPartID(s *string) *ItemPartTranslationUpdateOne {
	if s != nil {
		iptuo.SetItemPartID(*s)
	}
	return iptuo
}

// SetLanguageCode sets the "language_code" field.
func (iptuo *ItemPartTranslationUpdateOne) SetLanguageCode(s string) *ItemPartTranslationUpdateOne {
	iptuo.mutation.SetLanguageCode(s)
	return iptuo
}

// SetNillableLanguageCode sets the "language_code" field if the given value is not nil.
func (iptuo *ItemPartTranslationUpdateOne) SetNillableLanguageCode(s *string) *ItemPartTranslationUpdateOne {
	if s != nil {
		iptuo.SetLanguageCode(*s)
	}
	return iptuo
}

// SetBody sets the "body" field.
func (iptuo *ItemPartTranslationUpdateOne) SetBody(s string) *ItemPartTranslationUpdateOne {
	iptuo.mutation.SetBody(s)
	return iptuo
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (iptuo *ItemPartTranslationUpdateOne) SetNillableBody(s *string) *ItemPartTranslationUpdateOne {
	if s != nil {
		iptuo.SetBody(*s)
	}
	return iptuo
}

// SetItemPart sets the "item_part" edge to the ItemPart entity.
func (iptuo *ItemPartTranslationUpdateOne) SetItemPart(i *ItemPart) *ItemPartTranslationUpdateOne {
	return iptuo.SetItemPartID(i.ID)
}

// Mutation returns the ItemPartTranslationMutation object of the builder.
func (iptuo *ItemPartTranslationUpdateOne) Mutation() *ItemPartTranslationMutation {
	return iptuo.mutation
}

// ClearItemPart clears the "item_part" edge to the ItemPart entity.
func (iptuo *ItemPartTranslationUpdateOne) ClearItemPart() *ItemPartTranslationUpdateOne {
	iptuo.mutation.ClearItemPart()
	return iptuo
}

// Where appends a list predicates to the ItemPartTranslationUpdate builder.
func (iptuo *ItemPartTranslationUpdateOne) Where(ps ...predicate.ItemPartTranslation) *ItemPartTranslationUpdateOne {
	iptuo.mutation.Where(ps...)
	return iptuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (iptuo *ItemPartTranslationUpdateOne) Select(field string, fields ...string) *ItemPartTranslationUpdateOne {
	iptuo.fields = append([]string{field}, fields...)
	return iptuo
}

// Save executes the query and returns the updated ItemPartTranslation entity.
func (iptuo *ItemPartTranslationUpdateOne) Save(ctx context.Context) (*ItemPartTranslation, error) {
	return withHooks(ctx, iptuo.sqlSave, iptuo.mutation, iptuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iptuo *ItemPartTranslationUpdateOne) SaveX(ctx context.Context) *ItemPartTranslation {
	node, err := iptuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (iptuo *ItemPartTranslationUpdateOne) Exec(ctx context.Context) error {
	_, err := iptuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iptuo *ItemPartTranslationUpdateOne) ExecX(ctx context.Context) {
	if err := iptuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iptuo *ItemPartTranslationUpdateOne) check() error {
	if iptuo.mutation.ItemPartCleared() && len(iptuo.mutation.ItemPartIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ItemPartTranslation.item_part"`)
	}
	return nil
}

func (iptuo *ItemPartTranslationUpdateOne) sqlSave(ctx context.Context) (_node *ItemPartTranslation, err error) {
	if err := iptuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(itemparttranslation.Table, itemparttranslation.Columns, sqlgraph.NewFieldSpec(itemparttranslation.FieldID, field.TypeString))
	id, ok := iptuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ItemPartTranslation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := iptuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, itemparttranslation.FieldID)
		for _, f := range fields {
			if !itemparttranslation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != itemparttranslation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := iptuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iptuo.mutation.LanguageCode(); ok {
		_spec.SetField(itemparttranslation.FieldLanguageCode, field.TypeString, value)
	}
	if value, ok := iptuo.mutation.Body(); ok {
		_spec.SetField(itemparttranslation.FieldBody, field.TypeString, value)
	}
	if iptuo.mutation.ItemPartCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemparttranslation.ItemPartTable,
			Columns: []string{itemparttranslation.ItemPartColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(itempart.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iptuo.mutation.ItemPartIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemparttranslation.ItemPartTable,
			Columns: []string{itemparttranslation.ItemPartColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(itempart.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ItemPartTranslation{config: iptuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, iptuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{itemparttranslation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	iptuo.mutation.done = true
	return _node, nil
}
