// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"silan-backend/internal/ent/language"
	"silan-backend/internal/ent/moment"
	"silan-backend/internal/ent/momenttranslation"
	"silan-backend/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MomentTranslationUpdate is the builder for updating MomentTranslation entities.
type MomentTranslationUpdate struct {
	config
	hooks    []Hook
	mutation *MomentTranslationMutation
}

// Where appends a list predicates to the MomentTranslationUpdate builder.
func (mtu *MomentTranslationUpdate) Where(ps ...predicate.MomentTranslation) *MomentTranslationUpdate {
	mtu.mutation.Where(ps...)
	return mtu
}

// SetMomentID sets the "moment_id" field.
func (mtu *MomentTranslationUpdate) SetMomentID(s string) *MomentTranslationUpdate {
	mtu.mutation.SetMomentID(s)
	return mtu
}

// SetNillableMomentID sets the "moment_id" field if the given value is not nil.
func (mtu *MomentTranslationUpdate) SetNillableMomentID(s *string) *MomentTranslationUpdate {
	if s != nil {
		mtu.SetMomentID(*s)
	}
	return mtu
}

// SetLanguageCode sets the "language_code" field.
func (mtu *MomentTranslationUpdate) SetLanguageCode(s string) *MomentTranslationUpdate {
	mtu.mutation.SetLanguageCode(s)
	return mtu
}

// SetNillableLanguageCode sets the "language_code" field if the given value is not nil.
func (mtu *MomentTranslationUpdate) SetNillableLanguageCode(s *string) *MomentTranslationUpdate {
	if s != nil {
		mtu.SetLanguageCode(*s)
	}
	return mtu
}

// SetTitle sets the "title" field.
func (mtu *MomentTranslationUpdate) SetTitle(s string) *MomentTranslationUpdate {
	mtu.mutation.SetTitle(s)
	return mtu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (mtu *MomentTranslationUpdate) SetNillableTitle(s *string) *MomentTranslationUpdate {
	if s != nil {
		mtu.SetTitle(*s)
	}
	return mtu
}

// ClearTitle clears the value of the "title" field.
func (mtu *MomentTranslationUpdate) ClearTitle() *MomentTranslationUpdate {
	mtu.mutation.ClearTitle()
	return mtu
}

// SetDescription sets the "description" field.
func (mtu *MomentTranslationUpdate) SetDescription(s string) *MomentTranslationUpdate {
	mtu.mutation.SetDescription(s)
	return mtu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (mtu *MomentTranslationUpdate) SetNillableDescription(s *string) *MomentTranslationUpdate {
	if s != nil {
		mtu.SetDescription(*s)
	}
	return mtu
}

// ClearDescription clears the value of the "description" field.
func (mtu *MomentTranslationUpdate) ClearDescription() *MomentTranslationUpdate {
	mtu.mutation.ClearDescription()
	return mtu
}

// SetMoment sets the "moment" edge to the Moment entity.
func (mtu *MomentTranslationUpdate) SetMoment(m *Moment) *MomentTranslationUpdate {
	return mtu.SetMomentID(m.ID)
}

// SetLanguageID sets the "language" edge to the Language entity by ID.
func (mtu *MomentTranslationUpdate) SetLanguageID(id string) *MomentTranslationUpdate {
	mtu.mutation.SetLanguageID(id)
	return mtu
}

// SetLanguage sets the "language" edge to the Language entity.
func (mtu *MomentTranslationUpdate) SetLanguage(l *Language) *MomentTranslationUpdate {
	return mtu.SetLanguageID(l.ID)
}

// Mutation returns the MomentTranslationMutation object of the builder.
func (mtu *MomentTranslationUpdate) Mutation() *MomentTranslationMutation {
	return mtu.mutation
}

// ClearMoment clears the "moment" edge to the Moment entity.
func (mtu *MomentTranslationUpdate) ClearMoment() *MomentTranslationUpdate {
	mtu.mutation.ClearMoment()
	return mtu
}

// ClearLanguage clears the "language" edge to the Language entity.
func (mtu *MomentTranslationUpdate) ClearLanguage() *MomentTranslationUpdate {
	mtu.mutation.ClearLanguage()
	return mtu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mtu *MomentTranslationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mtu.sqlSave, mtu.mutation, mtu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mtu *MomentTranslationUpdate) SaveX(ctx context.Context) int {
	affected, err := mtu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mtu *MomentTranslationUpdate) Exec(ctx context.Context) error {
	_, err := mtu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mtu *MomentTranslationUpdate) ExecX(ctx context.Context) {
	if err := mtu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mtu *MomentTranslationUpdate) check() error {
	if v, ok := mtu.mutation.LanguageCode(); ok {
		if err := momenttranslation.LanguageCodeValidator(v); err != nil {
			return &ValidationError{Name: "language_code", err: fmt.Errorf(`ent: validator failed for field "MomentTranslation.language_code": %w`, err)}
		}
	}
	if v, ok := mtu.mutation.Title(); ok {
		if err := momenttranslation.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "MomentTranslation.title": %w`, err)}
		}
	}
	if mtu.mutation.MomentCleared() && len(mtu.mutation.MomentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MomentTranslation.moment"`)
	}
	if mtu.mutation.LanguageCleared() && len(mtu.mutation.LanguageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MomentTranslation.language"`)
	}
	return nil
}

func (mtu *MomentTranslationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mtu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(momenttranslation.Table, momenttranslation.Columns, sqlgraph.NewFieldSpec(momenttranslation.FieldID, field.TypeString))
	if ps := mtu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mtu.mutation.Title(); ok {
		_spec.SetField(momenttranslation.FieldTitle, field.TypeString, value)
	}
	if mtu.mutation.TitleCleared() {
		_spec.ClearField(momenttranslation.FieldTitle, field.TypeString)
	}
	if value, ok := mtu.mutation.Description(); ok {
		_spec.SetField(momenttranslation.FieldDescription, field.TypeString, value)
	}
	if mtu.mutation.DescriptionCleared() {
		_spec.ClearField(momenttranslation.FieldDescription, field.TypeString)
	}
	if mtu.mutation.CreatedAtCleared() {
		_spec.ClearField(momenttranslation.FieldCreatedAt, field.TypeTime)
	}
	if mtu.mutation.MomentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   momenttranslation.MomentTable,
			Columns: []string{momenttranslation.MomentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(moment.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mtu.mutation.MomentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   momenttranslation.MomentTable,
			Columns: []string{momenttranslation.MomentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(moment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if mtu.mutation.LanguageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   momenttranslation.LanguageTable,
			Columns: []string{momenttranslation.LanguageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(language.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mtu.mutation.LanguageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   momenttranslation.LanguageTable,
			Columns: []string{momenttranslation.LanguageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(language.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mtu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{momenttranslation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mtu.mutation.done = true
	return n, nil
}

// MomentTranslationUpdateOne is the builder for updating a single MomentTranslation entity.
type MomentTranslationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MomentTranslationMutation
}

// SetMomentID sets the "moment_id" field.
func (mtuo *MomentTranslationUpdateOne) SetMomentID(s string) *MomentTranslationUpdateOne {
	mtuo.mutation.SetMomentID(s)
	return mtuo
}

// SetNillableMomentID sets the "moment_id" field if the given value is not nil.
func (mtuo *MomentTranslationUpdateOne) SetNillableMomentID(s *string) *MomentTranslationUpdateOne {
	if s != nil {
		mtuo.SetMomentID(*s)
	}
	return mtuo
}

// SetLanguageCode sets the "language_code" field.
func (mtuo *MomentTranslationUpdateOne) SetLanguageCode(s string) *MomentTranslationUpdateOne {
	mtuo.mutation.SetLanguageCode(s)
	return mtuo
}

// SetNillableLanguageCode sets the "language_code" field if the given value is not nil.
func (mtuo *MomentTranslationUpdateOne) SetNillableLanguageCode(s *string) *MomentTranslationUpdateOne {
	if s != nil {
		mtuo.SetLanguageCode(*s)
	}
	return mtuo
}

// SetTitle sets the "title" field.
func (mtuo *MomentTranslationUpdateOne) SetTitle(s string) *MomentTranslationUpdateOne {
	mtuo.mutation.SetTitle(s)
	return mtuo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (mtuo *MomentTranslationUpdateOne) SetNillableTitle(s *string) *MomentTranslationUpdateOne {
	if s != nil {
		mtuo.SetTitle(*s)
	}
	return mtuo
}

// ClearTitle clears the value of the "title" field.
func (mtuo *MomentTranslationUpdateOne) ClearTitle() *MomentTranslationUpdateOne {
	mtuo.mutation.ClearTitle()
	return mtuo
}

// SetDescription sets the "description" field.
func (mtuo *MomentTranslationUpdateOne) SetDescription(s string) *MomentTranslationUpdateOne {
	mtuo.mutation.SetDescription(s)
	return mtuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (mtuo *MomentTranslationUpdateOne) SetNillableDescription(s *string) *MomentTranslationUpdateOne {
	if s != nil {
		mtuo.SetDescription(*s)
	}
	return mtuo
}

// ClearDescription clears the value of the "description" field.
func (mtuo *MomentTranslationUpdateOne) ClearDescription() *MomentTranslationUpdateOne {
	mtuo.mutation.ClearDescription()
	return mtuo
}

// SetMoment sets the "moment" edge to the Moment entity.
func (mtuo *MomentTranslationUpdateOne) SetMoment(m *Moment) *MomentTranslationUpdateOne {
	return mtuo.SetMomentID(m.ID)
}

// SetLanguageID sets the "language" edge to the Language entity by ID.
func (mtuo *MomentTranslationUpdateOne) SetLanguageID(id string) *MomentTranslationUpdateOne {
	mtuo.mutation.SetLanguageID(id)
	return mtuo
}

// SetLanguage sets the "language" edge to the Language entity.
func (mtuo *MomentTranslationUpdateOne) SetLanguage(l *Language) *MomentTranslationUpdateOne {
	return mtuo.SetLanguageID(l.ID)
}

// Mutation returns the MomentTranslationMutation object of the builder.
func (mtuo *MomentTranslationUpdateOne) Mutation() *MomentTranslationMutation {
	return mtuo.mutation
}

// ClearMoment clears the "moment" edge to the Moment entity.
func (mtuo *MomentTranslationUpdateOne) ClearMoment() *MomentTranslationUpdateOne {
	mtuo.mutation.ClearMoment()
	return mtuo
}

// ClearLanguage clears the "language" edge to the Language entity.
func (mtuo *MomentTranslationUpdateOne) ClearLanguage() *MomentTranslationUpdateOne {
	mtuo.mutation.ClearLanguage()
	return mtuo
}

// Where appends a list predicates to the MomentTranslationUpdate builder.
func (mtuo *MomentTranslationUpdateOne) Where(ps ...predicate.MomentTranslation) *MomentTranslationUpdateOne {
	mtuo.mutation.Where(ps...)
	return mtuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (mtuo *MomentTranslationUpdateOne) Select(field string, fields ...string) *MomentTranslationUpdateOne {
	mtuo.fields = append([]string{field}, fields...)
	return mtuo
}

// Save executes the query and returns the updated MomentTranslation entity.
func (mtuo *MomentTranslationUpdateOne) Save(ctx context.Context) (*MomentTranslation, error) {
	return withHooks(ctx, mtuo.sqlSave, mtuo.mutation, mtuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mtuo *MomentTranslationUpdateOne) SaveX(ctx context.Context) *MomentTranslation {
	node, err := mtuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (mtuo *MomentTranslationUpdateOne) Exec(ctx context.Context) error {
	_, err := mtuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mtuo *MomentTranslationUpdateOne) ExecX(ctx context.Context) {
	if err := mtuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mtuo *MomentTranslationUpdateOne) check() error {
	if v, ok := mtuo.mutation.LanguageCode(); ok {
		if err := momenttranslation.LanguageCodeValidator(v); err != nil {
			return &ValidationError{Name: "language_code", err: fmt.Errorf(`ent: validator failed for field "MomentTranslation.language_code": %w`, err)}
		}
	}
	if v, ok := mtuo.mutation.Title(); ok {
		if err := momenttranslation.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "MomentTranslation.title": %w`, err)}
		}
	}
	if mtuo.mutation.MomentCleared() && len(mtuo.mutation.MomentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MomentTranslation.moment"`)
	}
	if mtuo.mutation.LanguageCleared() && len(mtuo.mutation.LanguageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MomentTranslation.language"`)
	}
	return nil
}

func (mtuo *MomentTranslationUpdateOne) sqlSave(ctx context.Context) (_node *MomentTranslation, err error) {
	if err := mtuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(momenttranslation.Table, momenttranslation.Columns, sqlgraph.NewFieldSpec(momenttranslation.FieldID, field.TypeString))
	id, ok := mtuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MomentTranslation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := mtuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, momenttranslation.FieldID)
		for _, f := range fields {
			if !momenttranslation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != momenttranslation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := mtuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mtuo.mutation.Title(); ok {
		_spec.SetField(momenttranslation.FieldTitle, field.TypeString, value)
	}
	if mtuo.mutation.TitleCleared() {
		_spec.ClearField(momenttranslation.FieldTitle, field.TypeString)
	}
	if value, ok := mtuo.mutation.Description(); ok {
		_spec.SetField(momenttranslation.FieldDescription, field.TypeString, value)
	}
	if mtuo.mutation.DescriptionCleared() {
		_spec.ClearField(momenttranslation.FieldDescription, field.TypeString)
	}
	if mtuo.mutation.CreatedAtCleared() {
		_spec.ClearField(momenttranslation.FieldCreatedAt, field.TypeTime)
	}
	if mtuo.mutation.MomentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   momenttranslation.MomentTable,
			Columns: []string{momenttranslation.MomentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(moment.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mtuo.mutation.MomentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   momenttranslation.MomentTable,
			Columns: []string{momenttranslation.MomentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(moment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if mtuo.mutation.LanguageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   momenttranslation.LanguageTable,
			Columns: []string{momenttranslation.LanguageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(language.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mtuo.mutation.LanguageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   momenttranslation.LanguageTable,
			Columns: []string{momenttranslation.LanguageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(language.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MomentTranslation{config: mtuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, mtuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{momenttranslation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	mtuo.mutation.done = true
	return _node, nil
}
