// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"silan-backend/internal/ent/partentrytranslation"
	"silan-backend/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PartEntryTranslationDelete is the builder for deleting a PartEntryTranslation entity.
type PartEntryTranslationDelete struct {
	config
	hooks    []Hook
	mutation *PartEntryTranslationMutation
}

// Where appends a list predicates to the PartEntryTranslationDelete builder.
func (petd *PartEntryTranslationDelete) Where(ps ...predicate.PartEntryTranslation) *PartEntryTranslationDelete {
	petd.mutation.Where(ps...)
	return petd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (petd *PartEntryTranslationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, petd.sqlExec, petd.mutation, petd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (petd *PartEntryTranslationDelete) ExecX(ctx context.Context) int {
	n, err := petd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (petd *PartEntryTranslationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(partentrytranslation.Table, sqlgraph.NewFieldSpec(partentrytranslation.FieldID, field.TypeString))
	if ps := petd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, petd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	petd.mutation.done = true
	return affected, err
}

// PartEntryTranslationDeleteOne is the builder for deleting a single PartEntryTranslation entity.
type PartEntryTranslationDeleteOne struct {
	petd *PartEntryTranslationDelete
}

// Where appends a list predicates to the PartEntryTranslationDelete builder.
func (petdo *PartEntryTranslationDeleteOne) Where(ps ...predicate.PartEntryTranslation) *PartEntryTranslationDeleteOne {
	petdo.petd.mutation.Where(ps...)
	return petdo
}

// Exec executes the deletion query.
func (petdo *PartEntryTranslationDeleteOne) Exec(ctx context.Context) error {
	n, err := petdo.petd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{partentrytranslation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (petdo *PartEntryTranslationDeleteOne) ExecX(ctx context.Context) {
	if err := petdo.Exec(ctx); err != nil {
		panic(err)
	}
}
