// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"silan-backend/internal/ent/predicate"
	"silan-backend/internal/ent/project"
	"silan-backend/internal/ent/projectdetail"
	"silan-backend/internal/ent/projectdetailtranslation"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ProjectDetailUpdate is the builder for updating ProjectDetail entities.
type ProjectDetailUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectDetailMutation
}

// Where appends a list predicates to the ProjectDetailUpdate builder.
func (pdu *ProjectDetailUpdate) Where(ps ...predicate.ProjectDetail) *ProjectDetailUpdate {
	pdu.mutation.Where(ps...)
	return pdu
}

// SetProjectID sets the "project_id" field.
func (pdu *ProjectDetailUpdate) SetProjectID(u uuid.UUID) *ProjectDetailUpdate {
	pdu.mutation.SetProjectID(u)
	return pdu
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (pdu *ProjectDetailUpdate) SetNillableProjectID(u *uuid.UUID) *ProjectDetailUpdate {
	if u != nil {
		pdu.SetProjectID(*u)
	}
	return pdu
}

// SetProjectDetails sets the "project_details" field.
func (pdu *ProjectDetailUpdate) SetProjectDetails(s string) *ProjectDetailUpdate {
	pdu.mutation.SetProjectDetails(s)
	return pdu
}

// SetNillableProjectDetails sets the "project_details" field if the given value is not nil.
func (pdu *ProjectDetailUpdate) SetNillableProjectDetails(s *string) *ProjectDetailUpdate {
	if s != nil {
		pdu.SetProjectDetails(*s)
	}
	return pdu
}

// ClearProjectDetails clears the value of the "project_details" field.
func (pdu *ProjectDetailUpdate) ClearProjectDetails() *ProjectDetailUpdate {
	pdu.mutation.ClearProjectDetails()
	return pdu
}

// SetDependencies sets the "dependencies" field.
func (pdu *ProjectDetailUpdate) SetDependencies(s string) *ProjectDetailUpdate {
	pdu.mutation.SetDependencies(s)
	return pdu
}

// SetNillableDependencies sets the "dependencies" field if the given value is not nil.
func (pdu *ProjectDetailUpdate) SetNillableDependencies(s *string) *ProjectDetailUpdate {
	if s != nil {
		pdu.SetDependencies(*s)
	}
	return pdu
}

// ClearDependencies clears the value of the "dependencies" field.
func (pdu *ProjectDetailUpdate) ClearDependencies() *ProjectDetailUpdate {
	pdu.mutation.ClearDependencies()
	return pdu
}

// SetLicense sets the "license" field.
func (pdu *ProjectDetailUpdate) SetLicense(s string) *ProjectDetailUpdate {
	pdu.mutation.SetLicense(s)
	return pdu
}

// SetNillableLicense sets the "license" field if the given value is not nil.
func (pdu *ProjectDetailUpdate) SetNillableLicense(s *string) *ProjectDetailUpdate {
	if s != nil {
		pdu.SetLicense(*s)
	}
	return pdu
}

// ClearLicense clears the value of the "license" field.
func (pdu *ProjectDetailUpdate) ClearLicense() *ProjectDetailUpdate {
	pdu.mutation.ClearLicense()
	return pdu
}

// SetLicenseText sets the "license_text" field.
func (pdu *ProjectDetailUpdate) SetLicenseText(s string) *ProjectDetailUpdate {
	pdu.mutation.SetLicenseText(s)
	return pdu
}

// SetNillableLicenseText sets the "license_text" field if the given value is not nil.
func (pdu *ProjectDetailUpdate) SetNillableLicenseText(s *string) *ProjectDetailUpdate {
	if s != nil {
		pdu.SetLicenseText(*s)
	}
	return pdu
}

// ClearLicenseText clears the value of the "license_text" field.
func (pdu *ProjectDetailUpdate) ClearLicenseText() *ProjectDetailUpdate {
	pdu.mutation.ClearLicenseText()
	return pdu
}

// SetVersion sets the "version" field.
func (pdu *ProjectDetailUpdate) SetVersion(s string) *ProjectDetailUpdate {
	pdu.mutation.SetVersion(s)
	return pdu
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (pdu *ProjectDetailUpdate) SetNillableVersion(s *string) *ProjectDetailUpdate {
	if s != nil {
		pdu.SetVersion(*s)
	}
	return pdu
}

// ClearVersion clears the value of the "version" field.
func (pdu *ProjectDetailUpdate) ClearVersion() *ProjectDetailUpdate {
	pdu.mutation.ClearVersion()
	return pdu
}

// SetUpdatedAt sets the "updated_at" field.
func (pdu *ProjectDetailUpdate) SetUpdatedAt(t time.Time) *ProjectDetailUpdate {
	pdu.mutation.SetUpdatedAt(t)
	return pdu
}

// SetProject sets the "project" edge to the Project entity.
func (pdu *ProjectDetailUpdate) SetProject(p *Project) *ProjectDetailUpdate {
	return pdu.SetProjectID(p.ID)
}

// AddTranslationIDs adds the "translations" edge to the ProjectDetailTranslation entity by IDs.
func (pdu *ProjectDetailUpdate) AddTranslationIDs(ids ...uuid.UUID) *ProjectDetailUpdate {
	pdu.mutation.AddTranslationIDs(ids...)
	return pdu
}

// AddTranslations adds the "translations" edges to the ProjectDetailTranslation entity.
func (pdu *ProjectDetailUpdate) AddTranslations(p ...*ProjectDetailTranslation) *ProjectDetailUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pdu.AddTranslationIDs(ids...)
}

// Mutation returns the ProjectDetailMutation object of the builder.
func (pdu *ProjectDetailUpdate) Mutation() *ProjectDetailMutation {
	return pdu.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (pdu *ProjectDetailUpdate) ClearProject() *ProjectDetailUpdate {
	pdu.mutation.ClearProject()
	return pdu
}

// ClearTranslations clears all "translations" edges to the ProjectDetailTranslation entity.
func (pdu *ProjectDetailUpdate) ClearTranslations() *ProjectDetailUpdate {
	pdu.mutation.ClearTranslations()
	return pdu
}

// RemoveTranslationIDs removes the "translations" edge to ProjectDetailTranslation entities by IDs.
func (pdu *ProjectDetailUpdate) RemoveTranslationIDs(ids ...uuid.UUID) *ProjectDetailUpdate {
	pdu.mutation.RemoveTranslationIDs(ids...)
	return pdu
}

// RemoveTranslations removes "translations" edges to ProjectDetailTranslation entities.
func (pdu *ProjectDetailUpdate) RemoveTranslations(p ...*ProjectDetailTranslation) *ProjectDetailUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pdu.RemoveTranslationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pdu *ProjectDetailUpdate) Save(ctx context.Context) (int, error) {
	pdu.defaults()
	return withHooks(ctx, pdu.sqlSave, pdu.mutation, pdu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pdu *ProjectDetailUpdate) SaveX(ctx context.Context) int {
	affected, err := pdu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pdu *ProjectDetailUpdate) Exec(ctx context.Context) error {
	_, err := pdu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pdu *ProjectDetailUpdate) ExecX(ctx context.Context) {
	if err := pdu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pdu *ProjectDetailUpdate) defaults() {
	if _, ok := pdu.mutation.UpdatedAt(); !ok {
		v := projectdetail.UpdateDefaultUpdatedAt()
		pdu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pdu *ProjectDetailUpdate) check() error {
	if v, ok := pdu.mutation.License(); ok {
		if err := projectdetail.LicenseValidator(v); err != nil {
			return &ValidationError{Name: "license", err: fmt.Errorf(`ent: validator failed for field "ProjectDetail.license": %w`, err)}
		}
	}
	if v, ok := pdu.mutation.Version(); ok {
		if err := projectdetail.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ProjectDetail.version": %w`, err)}
		}
	}
	if pdu.mutation.ProjectCleared() && len(pdu.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectDetail.project"`)
	}
	return nil
}

func (pdu *ProjectDetailUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pdu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(projectdetail.Table, projectdetail.Columns, sqlgraph.NewFieldSpec(projectdetail.FieldID, field.TypeUUID))
	if ps := pdu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pdu.mutation.ProjectDetails(); ok {
		_spec.SetField(projectdetail.FieldProjectDetails, field.TypeString, value)
	}
	if pdu.mutation.ProjectDetailsCleared() {
		_spec.ClearField(projectdetail.FieldProjectDetails, field.TypeString)
	}
	if value, ok := pdu.mutation.Dependencies(); ok {
		_spec.SetField(projectdetail.FieldDependencies, field.TypeString, value)
	}
	if pdu.mutation.DependenciesCleared() {
		_spec.ClearField(projectdetail.FieldDependencies, field.TypeString)
	}
	if value, ok := pdu.mutation.License(); ok {
		_spec.SetField(projectdetail.FieldLicense, field.TypeString, value)
	}
	if pdu.mutation.LicenseCleared() {
		_spec.ClearField(projectdetail.FieldLicense, field.TypeString)
	}
	if value, ok := pdu.mutation.LicenseText(); ok {
		_spec.SetField(projectdetail.FieldLicenseText, field.TypeString, value)
	}
	if pdu.mutation.LicenseTextCleared() {
		_spec.ClearField(projectdetail.FieldLicenseText, field.TypeString)
	}
	if value, ok := pdu.mutation.Version(); ok {
		_spec.SetField(projectdetail.FieldVersion, field.TypeString, value)
	}
	if pdu.mutation.VersionCleared() {
		_spec.ClearField(projectdetail.FieldVersion, field.TypeString)
	}
	if value, ok := pdu.mutation.UpdatedAt(); ok {
		_spec.SetField(projectdetail.FieldUpdatedAt, field.TypeTime, value)
	}
	if pdu.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   projectdetail.ProjectTable,
			Columns: []string{projectdetail.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pdu.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   projectdetail.ProjectTable,
			Columns: []string{projectdetail.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pdu.mutation.TranslationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   projectdetail.TranslationsTable,
			Columns: []string{projectdetail.TranslationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectdetailtranslation.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pdu.mutation.RemovedTranslationsIDs(); len(nodes) > 0 && !pdu.mutation.TranslationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   projectdetail.TranslationsTable,
			Columns: []string{projectdetail.TranslationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectdetailtranslation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pdu.mutation.TranslationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   projectdetail.TranslationsTable,
			Columns: []string{projectdetail.TranslationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectdetailtranslation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pdu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projectdetail.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pdu.mutation.done = true
	return n, nil
}

// ProjectDetailUpdateOne is the builder for updating a single ProjectDetail entity.
type ProjectDetailUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectDetailMutation
}

// SetProjectID sets the "project_id" field.
func (pduo *ProjectDetailUpdateOne) SetProjectID(u uuid.UUID) *ProjectDetailUpdateOne {
	pduo.mutation.SetProjectID(u)
	return pduo
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (pduo *ProjectDetailUpdateOne) SetNillableProjectID(u *uuid.UUID) *ProjectDetailUpdateOne {
	if u != nil {
		pduo.SetProjectID(*u)
	}
	return pduo
}

// SetProjectDetails sets the "project_details" field.
func (pduo *ProjectDetailUpdateOne) SetProjectDetails(s string) *ProjectDetailUpdateOne {
	pduo.mutation.SetProjectDetails(s)
	return pduo
}

// SetNillableProjectDetails sets the "project_details" field if the given value is not nil.
func (pduo *ProjectDetailUpdateOne) SetNillableProjectDetails(s *string) *ProjectDetailUpdateOne {
	if s != nil {
		pduo.SetProjectDetails(*s)
	}
	return pduo
}

// ClearProjectDetails clears the value of the "project_details" field.
func (pduo *ProjectDetailUpdateOne) ClearProjectDetails() *ProjectDetailUpdateOne {
	pduo.mutation.ClearProjectDetails()
	return pduo
}

// SetDependencies sets the "dependencies" field.
func (pduo *ProjectDetailUpdateOne) SetDependencies(s string) *ProjectDetailUpdateOne {
	pduo.mutation.SetDependencies(s)
	return pduo
}

// SetNillableDependencies sets the "dependencies" field if the given value is not nil.
func (pduo *ProjectDetailUpdateOne) SetNillableDependencies(s *string) *ProjectDetailUpdateOne {
	if s != nil {
		pduo.SetDependencies(*s)
	}
	return pduo
}

// ClearDependencies clears the value of the "dependencies" field.
func (pduo *ProjectDetailUpdateOne) ClearDependencies() *ProjectDetailUpdateOne {
	pduo.mutation.ClearDependencies()
	return pduo
}

// SetLicense sets the "license" field.
func (pduo *ProjectDetailUpdateOne) SetLicense(s string) *ProjectDetailUpdateOne {
	pduo.mutation.SetLicense(s)
	return pduo
}

// SetNillableLicense sets the "license" field if the given value is not nil.
func (pduo *ProjectDetailUpdateOne) SetNillableLicense(s *string) *ProjectDetailUpdateOne {
	if s != nil {
		pduo.SetLicense(*s)
	}
	return pduo
}

// ClearLicense clears the value of the "license" field.
func (pduo *ProjectDetailUpdateOne) ClearLicense() *ProjectDetailUpdateOne {
	pduo.mutation.ClearLicense()
	return pduo
}

// SetLicenseText sets the "license_text" field.
func (pduo *ProjectDetailUpdateOne) SetLicenseText(s string) *ProjectDetailUpdateOne {
	pduo.mutation.SetLicenseText(s)
	return pduo
}

// SetNillableLicenseText sets the "license_text" field if the given value is not nil.
func (pduo *ProjectDetailUpdateOne) SetNillableLicenseText(s *string) *ProjectDetailUpdateOne {
	if s != nil {
		pduo.SetLicenseText(*s)
	}
	return pduo
}

// ClearLicenseText clears the value of the "license_text" field.
func (pduo *ProjectDetailUpdateOne) ClearLicenseText() *ProjectDetailUpdateOne {
	pduo.mutation.ClearLicenseText()
	return pduo
}

// SetVersion sets the "version" field.
func (pduo *ProjectDetailUpdateOne) SetVersion(s string) *ProjectDetailUpdateOne {
	pduo.mutation.SetVersion(s)
	return pduo
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (pduo *ProjectDetailUpdateOne) SetNillableVersion(s *string) *ProjectDetailUpdateOne {
	if s != nil {
		pduo.SetVersion(*s)
	}
	return pduo
}

// ClearVersion clears the value of the "version" field.
func (pduo *ProjectDetailUpdateOne) ClearVersion() *ProjectDetailUpdateOne {
	pduo.mutation.ClearVersion()
	return pduo
}

// SetUpdatedAt sets the "updated_at" field.
func (pduo *ProjectDetailUpdateOne) SetUpdatedAt(t time.Time) *ProjectDetailUpdateOne {
	pduo.mutation.SetUpdatedAt(t)
	return pduo
}

// SetProject sets the "project" edge to the Project entity.
func (pduo *ProjectDetailUpdateOne) SetProject(p *Project) *ProjectDetailUpdateOne {
	return pduo.SetProjectID(p.ID)
}

// AddTranslationIDs adds the "translations" edge to the ProjectDetailTranslation entity by IDs.
func (pduo *ProjectDetailUpdateOne) AddTranslationIDs(ids ...uuid.UUID) *ProjectDetailUpdateOne {
	pduo.mutation.AddTranslationIDs(ids...)
	return pduo
}

// AddTranslations adds the "translations" edges to the ProjectDetailTranslation entity.
func (pduo *ProjectDetailUpdateOne) AddTranslations(p ...*ProjectDetailTranslation) *ProjectDetailUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pduo.AddTranslationIDs(ids...)
}

// Mutation returns the ProjectDetailMutation object of the builder.
func (pduo *ProjectDetailUpdateOne) Mutation() *ProjectDetailMutation {
	return pduo.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (pduo *ProjectDetailUpdateOne) ClearProject() *ProjectDetailUpdateOne {
	pduo.mutation.ClearProject()
	return pduo
}

// ClearTranslations clears all "translations" edges to the ProjectDetailTranslation entity.
func (pduo *ProjectDetailUpdateOne) ClearTranslations() *ProjectDetailUpdateOne {
	pduo.mutation.ClearTranslations()
	return pduo
}

// RemoveTranslationIDs removes the "translations" edge to ProjectDetailTranslation entities by IDs.
func (pduo *ProjectDetailUpdateOne) RemoveTranslationIDs(ids ...uuid.UUID) *ProjectDetailUpdateOne {
	pduo.mutation.RemoveTranslationIDs(ids...)
	return pduo
}

// RemoveTranslations removes "translations" edges to ProjectDetailTranslation entities.
func (pduo *ProjectDetailUpdateOne) RemoveTranslations(p ...*ProjectDetailTranslation) *ProjectDetailUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pduo.RemoveTranslationIDs(ids...)
}

// Where appends a list predicates to the ProjectDetailUpdate builder.
func (pduo *ProjectDetailUpdateOne) Where(ps ...predicate.ProjectDetail) *ProjectDetailUpdateOne {
	pduo.mutation.Where(ps...)
	return pduo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (pduo *ProjectDetailUpdateOne) Select(field string, fields ...string) *ProjectDetailUpdateOne {
	pduo.fields = append([]string{field}, fields...)
	return pduo
}

// Save executes the query and returns the updated ProjectDetail entity.
func (pduo *ProjectDetailUpdateOne) Save(ctx context.Context) (*ProjectDetail, error) {
	pduo.defaults()
	return withHooks(ctx, pduo.sqlSave, pduo.mutation, pduo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pduo *ProjectDetailUpdateOne) SaveX(ctx context.Context) *ProjectDetail {
	node, err := pduo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pduo *ProjectDetailUpdateOne) Exec(ctx context.Context) error {
	_, err := pduo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pduo *ProjectDetailUpdateOne) ExecX(ctx context.Context) {
	if err := pduo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pduo *ProjectDetailUpdateOne) defaults() {
	if _, ok := pduo.mutation.UpdatedAt(); !ok {
		v := projectdetail.UpdateDefaultUpdatedAt()
		pduo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pduo *ProjectDetailUpdateOne) check() error {
	if v, ok := pduo.mutation.License(); ok {
		if err := projectdetail.LicenseValidator(v); err != nil {
			return &ValidationError{Name: "license", err: fmt.Errorf(`ent: validator failed for field "ProjectDetail.license": %w`, err)}
		}
	}
	if v, ok := pduo.mutation.Version(); ok {
		if err := projectdetail.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ProjectDetail.version": %w`, err)}
		}
	}
	if pduo.mutation.ProjectCleared() && len(pduo.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectDetail.project"`)
	}
	return nil
}

func (pduo *ProjectDetailUpdateOne) sqlSave(ctx context.Context) (_node *ProjectDetail, err error) {
	if err := pduo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(projectdetail.Table, projectdetail.Columns, sqlgraph.NewFieldSpec(projectdetail.FieldID, field.TypeUUID))
	id, ok := pduo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProjectDetail.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := pduo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, projectdetail.FieldID)
		for _, f := range fields {
			if !projectdetail.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != projectdetail.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := pduo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pduo.mutation.ProjectDetails(); ok {
		_spec.SetField(projectdetail.FieldProjectDetails, field.TypeString, value)
	}
	if pduo.mutation.ProjectDetailsCleared() {
		_spec.ClearField(projectdetail.FieldProjectDetails, field.TypeString)
	}
	if value, ok := pduo.mutation.Dependencies(); ok {
		_spec.SetField(projectdetail.FieldDependencies, field.TypeString, value)
	}
	if pduo.mutation.DependenciesCleared() {
		_spec.ClearField(projectdetail.FieldDependencies, field.TypeString)
	}
	if value, ok := pduo.mutation.License(); ok {
		_spec.SetField(projectdetail.FieldLicense, field.TypeString, value)
	}
	if pduo.mutation.LicenseCleared() {
		_spec.ClearField(projectdetail.FieldLicense, field.TypeString)
	}
	if value, ok := pduo.mutation.LicenseText(); ok {
		_spec.SetField(projectdetail.FieldLicenseText, field.TypeString, value)
	}
	if pduo.mutation.LicenseTextCleared() {
		_spec.ClearField(projectdetail.FieldLicenseText, field.TypeString)
	}
	if value, ok := pduo.mutation.Version(); ok {
		_spec.SetField(projectdetail.FieldVersion, field.TypeString, value)
	}
	if pduo.mutation.VersionCleared() {
		_spec.ClearField(projectdetail.FieldVersion, field.TypeString)
	}
	if value, ok := pduo.mutation.UpdatedAt(); ok {
		_spec.SetField(projectdetail.FieldUpdatedAt, field.TypeTime, value)
	}
	if pduo.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   projectdetail.ProjectTable,
			Columns: []string{projectdetail.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pduo.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   projectdetail.ProjectTable,
			Columns: []string{projectdetail.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pduo.mutation.TranslationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   projectdetail.TranslationsTable,
			Columns: []string{projectdetail.TranslationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectdetailtranslation.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pduo.mutation.RemovedTranslationsIDs(); len(nodes) > 0 && !pduo.mutation.TranslationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   projectdetail.TranslationsTable,
			Columns: []string{projectdetail.TranslationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectdetailtranslation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pduo.mutation.TranslationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   projectdetail.TranslationsTable,
			Columns: []string{projectdetail.TranslationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectdetailtranslation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProjectDetail{config: pduo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pduo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projectdetail.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	pduo.mutation.done = true
	return _node, nil
}
