// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"silan-backend/internal/ent/predicate"
	"silan-backend/internal/ent/statscachevisitor"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StatsCacheVisitorUpdate is the builder for updating StatsCacheVisitor entities.
type StatsCacheVisitorUpdate struct {
	config
	hooks    []Hook
	mutation *StatsCacheVisitorMutation
}

// Where appends a list predicates to the StatsCacheVisitorUpdate builder.
func (scvu *StatsCacheVisitorUpdate) Where(ps ...predicate.StatsCacheVisitor) *StatsCacheVisitorUpdate {
	scvu.mutation.Where(ps...)
	return scvu
}

// SetEntityType sets the "entity_type" field.
func (scvu *StatsCacheVisitorUpdate) SetEntityType(st statscachevisitor.EntityType) *StatsCacheVisitorUpdate {
	scvu.mutation.SetEntityType(st)
	return scvu
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (scvu *StatsCacheVisitorUpdate) SetNillableEntityType(st *statscachevisitor.EntityType) *StatsCacheVisitorUpdate {
	if st != nil {
		scvu.SetEntityType(*st)
	}
	return scvu
}

// SetEntityID sets the "entity_id" field.
func (scvu *StatsCacheVisitorUpdate) SetEntityID(s string) *StatsCacheVisitorUpdate {
	scvu.mutation.SetEntityID(s)
	return scvu
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (scvu *StatsCacheVisitorUpdate) SetNillableEntityID(s *string) *StatsCacheVisitorUpdate {
	if s != nil {
		scvu.SetEntityID(*s)
	}
	return scvu
}

// SetFingerprint sets the "fingerprint" field.
func (scvu *StatsCacheVisitorUpdate) SetFingerprint(s string) *StatsCacheVisitorUpdate {
	scvu.mutation.SetFingerprint(s)
	return scvu
}

// SetNillableFingerprint sets the "fingerprint" field if the given value is not nil.
func (scvu *StatsCacheVisitorUpdate) SetNillableFingerprint(s *string) *StatsCacheVisitorUpdate {
	if s != nil {
		scvu.SetFingerprint(*s)
	}
	return scvu
}

// SetIPMasked sets the "ip_masked" field.
func (scvu *StatsCacheVisitorUpdate) SetIPMasked(s string) *StatsCacheVisitorUpdate {
	scvu.mutation.SetIPMasked(s)
	return scvu
}

// SetNillableIPMasked sets the "ip_masked" field if the given value is not nil.
func (scvu *StatsCacheVisitorUpdate) SetNillableIPMasked(s *string) *StatsCacheVisitorUpdate {
	if s != nil {
		scvu.SetIPMasked(*s)
	}
	return scvu
}

// SetVisitorKind sets the "visitor_kind" field.
func (scvu *StatsCacheVisitorUpdate) SetVisitorKind(sk statscachevisitor.VisitorKind) *StatsCacheVisitorUpdate {
	scvu.mutation.SetVisitorKind(sk)
	return scvu
}

// SetNillableVisitorKind sets the "visitor_kind" field if the given value is not nil.
func (scvu *StatsCacheVisitorUpdate) SetNillableVisitorKind(sk *statscachevisitor.VisitorKind) *StatsCacheVisitorUpdate {
	if sk != nil {
		scvu.SetVisitorKind(*sk)
	}
	return scvu
}

// SetReferrerKind sets the "referrer_kind" field.
func (scvu *StatsCacheVisitorUpdate) SetReferrerKind(sk statscachevisitor.ReferrerKind) *StatsCacheVisitorUpdate {
	scvu.mutation.SetReferrerKind(sk)
	return scvu
}

// SetNillableReferrerKind sets the "referrer_kind" field if the given value is not nil.
func (scvu *StatsCacheVisitorUpdate) SetNillableReferrerKind(sk *statscachevisitor.ReferrerKind) *StatsCacheVisitorUpdate {
	if sk != nil {
		scvu.SetReferrerKind(*sk)
	}
	return scvu
}

// SetLastSeenAt sets the "last_seen_at" field.
func (scvu *StatsCacheVisitorUpdate) SetLastSeenAt(t time.Time) *StatsCacheVisitorUpdate {
	scvu.mutation.SetLastSeenAt(t)
	return scvu
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (scvu *StatsCacheVisitorUpdate) SetNillableLastSeenAt(t *time.Time) *StatsCacheVisitorUpdate {
	if t != nil {
		scvu.SetLastSeenAt(*t)
	}
	return scvu
}

// SetSyncedAt sets the "synced_at" field.
func (scvu *StatsCacheVisitorUpdate) SetSyncedAt(t time.Time) *StatsCacheVisitorUpdate {
	scvu.mutation.SetSyncedAt(t)
	return scvu
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (scvu *StatsCacheVisitorUpdate) SetNillableSyncedAt(t *time.Time) *StatsCacheVisitorUpdate {
	if t != nil {
		scvu.SetSyncedAt(*t)
	}
	return scvu
}

// Mutation returns the StatsCacheVisitorMutation object of the builder.
func (scvu *StatsCacheVisitorUpdate) Mutation() *StatsCacheVisitorMutation {
	return scvu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (scvu *StatsCacheVisitorUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, scvu.sqlSave, scvu.mutation, scvu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (scvu *StatsCacheVisitorUpdate) SaveX(ctx context.Context) int {
	affected, err := scvu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (scvu *StatsCacheVisitorUpdate) Exec(ctx context.Context) error {
	_, err := scvu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scvu *StatsCacheVisitorUpdate) ExecX(ctx context.Context) {
	if err := scvu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (scvu *StatsCacheVisitorUpdate) check() error {
	if v, ok := scvu.mutation.EntityType(); ok {
		if err := statscachevisitor.EntityTypeValidator(v); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "StatsCacheVisitor.entity_type": %w`, err)}
		}
	}
	if v, ok := scvu.mutation.VisitorKind(); ok {
		if err := statscachevisitor.VisitorKindValidator(v); err != nil {
			return &ValidationError{Name: "visitor_kind", err: fmt.Errorf(`ent: validator failed for field "StatsCacheVisitor.visitor_kind": %w`, err)}
		}
	}
	if v, ok := scvu.mutation.ReferrerKind(); ok {
		if err := statscachevisitor.ReferrerKindValidator(v); err != nil {
			return &ValidationError{Name: "referrer_kind", err: fmt.Errorf(`ent: validator failed for field "StatsCacheVisitor.referrer_kind": %w`, err)}
		}
	}
	return nil
}

func (scvu *StatsCacheVisitorUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := scvu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(statscachevisitor.Table, statscachevisitor.Columns, sqlgraph.NewFieldSpec(statscachevisitor.FieldID, field.TypeInt))
	if ps := scvu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := scvu.mutation.EntityType(); ok {
		_spec.SetField(statscachevisitor.FieldEntityType, field.TypeEnum, value)
	}
	if value, ok := scvu.mutation.EntityID(); ok {
		_spec.SetField(statscachevisitor.FieldEntityID, field.TypeString, value)
	}
	if value, ok := scvu.mutation.Fingerprint(); ok {
		_spec.SetField(statscachevisitor.FieldFingerprint, field.TypeString, value)
	}
	if value, ok := scvu.mutation.IPMasked(); ok {
		_spec.SetField(statscachevisitor.FieldIPMasked, field.TypeString, value)
	}
	if value, ok := scvu.mutation.VisitorKind(); ok {
		_spec.SetField(statscachevisitor.FieldVisitorKind, field.TypeEnum, value)
	}
	if value, ok := scvu.mutation.ReferrerKind(); ok {
		_spec.SetField(statscachevisitor.FieldReferrerKind, field.TypeEnum, value)
	}
	if value, ok := scvu.mutation.LastSeenAt(); ok {
		_spec.SetField(statscachevisitor.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := scvu.mutation.SyncedAt(); ok {
		_spec.SetField(statscachevisitor.FieldSyncedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, scvu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{statscachevisitor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	scvu.mutation.done = true
	return n, nil
}

// StatsCacheVisitorUpdateOne is the builder for updating a single StatsCacheVisitor entity.
type StatsCacheVisitorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StatsCacheVisitorMutation
}

// SetEntityType sets the "entity_type" field.
func (scvuo *StatsCacheVisitorUpdateOne) SetEntityType(st statscachevisitor.EntityType) *StatsCacheVisitorUpdateOne {
	scvuo.mutation.SetEntityType(st)
	return scvuo
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (scvuo *StatsCacheVisitorUpdateOne) SetNillableEntityType(st *statscachevisitor.EntityType) *StatsCacheVisitorUpdateOne {
	if st != nil {
		scvuo.SetEntityType(*st)
	}
	return scvuo
}

// SetEntityID sets the "entity_id" field.
func (scvuo *StatsCacheVisitorUpdateOne) SetEntityID(s string) *StatsCacheVisitorUpdateOne {
	scvuo.mutation.SetEntityID(s)
	return scvuo
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (scvuo *StatsCacheVisitorUpdateOne) SetNillableEntityID(s *string) *StatsCacheVisitorUpdateOne {
	if s != nil {
		scvuo.SetEntityID(*s)
	}
	return scvuo
}

// SetFingerprint sets the "fingerprint" field.
func (scvuo *StatsCacheVisitorUpdateOne) SetFingerprint(s string) *StatsCacheVisitorUpdateOne {
	scvuo.mutation.SetFingerprint(s)
	return scvuo
}

// SetNillableFingerprint sets the "fingerprint" field if the given value is not nil.
func (scvuo *StatsCacheVisitorUpdateOne) SetNillableFingerprint(s *string) *StatsCacheVisitorUpdateOne {
	if s != nil {
		scvuo.SetFingerprint(*s)
	}
	return scvuo
}

// SetIPMasked sets the "ip_masked" field.
func (scvuo *StatsCacheVisitorUpdateOne) SetIPMasked(s string) *StatsCacheVisitorUpdateOne {
	scvuo.mutation.SetIPMasked(s)
	return scvuo
}

// SetNillableIPMasked sets the "ip_masked" field if the given value is not nil.
func (scvuo *StatsCacheVisitorUpdateOne) SetNillableIPMasked(s *string) *StatsCacheVisitorUpdateOne {
	if s != nil {
		scvuo.SetIPMasked(*s)
	}
	return scvuo
}

// SetVisitorKind sets the "visitor_kind" field.
func (scvuo *StatsCacheVisitorUpdateOne) SetVisitorKind(sk statscachevisitor.VisitorKind) *StatsCacheVisitorUpdateOne {
	scvuo.mutation.SetVisitorKind(sk)
	return scvuo
}

// SetNillableVisitorKind sets the "visitor_kind" field if the given value is not nil.
func (scvuo *StatsCacheVisitorUpdateOne) SetNillableVisitorKind(sk *statscachevisitor.VisitorKind) *StatsCacheVisitorUpdateOne {
	if sk != nil {
		scvuo.SetVisitorKind(*sk)
	}
	return scvuo
}

// SetReferrerKind sets the "referrer_kind" field.
func (scvuo *StatsCacheVisitorUpdateOne) SetReferrerKind(sk statscachevisitor.ReferrerKind) *StatsCacheVisitorUpdateOne {
	scvuo.mutation.SetReferrerKind(sk)
	return scvuo
}

// SetNillableReferrerKind sets the "referrer_kind" field if the given value is not nil.
func (scvuo *StatsCacheVisitorUpdateOne) SetNillableReferrerKind(sk *statscachevisitor.ReferrerKind) *StatsCacheVisitorUpdateOne {
	if sk != nil {
		scvuo.SetReferrerKind(*sk)
	}
	return scvuo
}

// SetLastSeenAt sets the "last_seen_at" field.
func (scvuo *StatsCacheVisitorUpdateOne) SetLastSeenAt(t time.Time) *StatsCacheVisitorUpdateOne {
	scvuo.mutation.SetLastSeenAt(t)
	return scvuo
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (scvuo *StatsCacheVisitorUpdateOne) SetNillableLastSeenAt(t *time.Time) *StatsCacheVisitorUpdateOne {
	if t != nil {
		scvuo.SetLastSeenAt(*t)
	}
	return scvuo
}

// SetSyncedAt sets the "synced_at" field.
func (scvuo *StatsCacheVisitorUpdateOne) SetSyncedAt(t time.Time) *StatsCacheVisitorUpdateOne {
	scvuo.mutation.SetSyncedAt(t)
	return scvuo
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (scvuo *StatsCacheVisitorUpdateOne) SetNillableSyncedAt(t *time.Time) *StatsCacheVisitorUpdateOne {
	if t != nil {
		scvuo.SetSyncedAt(*t)
	}
	return scvuo
}

// Mutation returns the StatsCacheVisitorMutation object of the builder.
func (scvuo *StatsCacheVisitorUpdateOne) Mutation() *StatsCacheVisitorMutation {
	return scvuo.mutation
}

// Where appends a list predicates to the StatsCacheVisitorUpdate builder.
func (scvuo *StatsCacheVisitorUpdateOne) Where(ps ...predicate.StatsCacheVisitor) *StatsCacheVisitorUpdateOne {
	scvuo.mutation.Where(ps...)
	return scvuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (scvuo *StatsCacheVisitorUpdateOne) Select(field string, fields ...string) *StatsCacheVisitorUpdateOne {
	scvuo.fields = append([]string{field}, fields...)
	return scvuo
}

// Save executes the query and returns the updated StatsCacheVisitor entity.
func (scvuo *StatsCacheVisitorUpdateOne) Save(ctx context.Context) (*StatsCacheVisitor, error) {
	return withHooks(ctx, scvuo.sqlSave, scvuo.mutation, scvuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (scvuo *StatsCacheVisitorUpdateOne) SaveX(ctx context.Context) *StatsCacheVisitor {
	node, err := scvuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (scvuo *StatsCacheVisitorUpdateOne) Exec(ctx context.Context) error {
	_, err := scvuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scvuo *StatsCacheVisitorUpdateOne) ExecX(ctx context.Context) {
	if err := scvuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (scvuo *StatsCacheVisitorUpdateOne) check() error {
	if v, ok := scvuo.mutation.EntityType(); ok {
		if err := statscachevisitor.EntityTypeValidator(v); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "StatsCacheVisitor.entity_type": %w`, err)}
		}
	}
	if v, ok := scvuo.mutation.VisitorKind(); ok {
		if err := statscachevisitor.VisitorKindValidator(v); err != nil {
			return &ValidationError{Name: "visitor_kind", err: fmt.Errorf(`ent: validator failed for field "StatsCacheVisitor.visitor_kind": %w`, err)}
		}
	}
	if v, ok := scvuo.mutation.ReferrerKind(); ok {
		if err := statscachevisitor.ReferrerKindValidator(v); err != nil {
			return &ValidationError{Name: "referrer_kind", err: fmt.Errorf(`ent: validator failed for field "StatsCacheVisitor.referrer_kind": %w`, err)}
		}
	}
	return nil
}

func (scvuo *StatsCacheVisitorUpdateOne) sqlSave(ctx context.Context) (_node *StatsCacheVisitor, err error) {
	if err := scvuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(statscachevisitor.Table, statscachevisitor.Columns, sqlgraph.NewFieldSpec(statscachevisitor.FieldID, field.TypeInt))
	id, ok := scvuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StatsCacheVisitor.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := scvuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, statscachevisitor.FieldID)
		for _, f := range fields {
			if !statscachevisitor.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != statscachevisitor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := scvuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := scvuo.mutation.EntityType(); ok {
		_spec.SetField(statscachevisitor.FieldEntityType, field.TypeEnum, value)
	}
	if value, ok := scvuo.mutation.EntityID(); ok {
		_spec.SetField(statscachevisitor.FieldEntityID, field.TypeString, value)
	}
	if value, ok := scvuo.mutation.Fingerprint(); ok {
		_spec.SetField(statscachevisitor.FieldFingerprint, field.TypeString, value)
	}
	if value, ok := scvuo.mutation.IPMasked(); ok {
		_spec.SetField(statscachevisitor.FieldIPMasked, field.TypeString, value)
	}
	if value, ok := scvuo.mutation.VisitorKind(); ok {
		_spec.SetField(statscachevisitor.FieldVisitorKind, field.TypeEnum, value)
	}
	if value, ok := scvuo.mutation.ReferrerKind(); ok {
		_spec.SetField(statscachevisitor.FieldReferrerKind, field.TypeEnum, value)
	}
	if value, ok := scvuo.mutation.LastSeenAt(); ok {
		_spec.SetField(statscachevisitor.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := scvuo.mutation.SyncedAt(); ok {
		_spec.SetField(statscachevisitor.FieldSyncedAt, field.TypeTime, value)
	}
	_node = &StatsCacheVisitor{config: scvuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, scvuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{statscachevisitor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	scvuo.mutation.done = true
	return _node, nil
}
