// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"silan-backend/internal/ent/statscachecrawler"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// StatsCacheCrawler is the model entity for the StatsCacheCrawler schema.
type StatsCacheCrawler struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// EntityType holds the value of the "entity_type" field.
	EntityType statscachecrawler.EntityType `json:"entity_type,omitempty"`
	// EntityID holds the value of the "entity_id" field.
	EntityID string `json:"entity_id,omitempty"`
	// VisitorKind holds the value of the "visitor_kind" field.
	VisitorKind statscachecrawler.VisitorKind `json:"visitor_kind,omitempty"`
	// Count holds the value of the "count" field.
	Count int `json:"count,omitempty"`
	// SyncedAt holds the value of the "synced_at" field.
	SyncedAt     time.Time `json:"synced_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StatsCacheCrawler) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case statscachecrawler.FieldID, statscachecrawler.FieldCount:
			values[i] = new(sql.NullInt64)
		case statscachecrawler.FieldEntityType, statscachecrawler.FieldEntityID, statscachecrawler.FieldVisitorKind:
			values[i] = new(sql.NullString)
		case statscachecrawler.FieldSyncedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StatsCacheCrawler fields.
func (scc *StatsCacheCrawler) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case statscachecrawler.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			scc.ID = int(value.Int64)
		case statscachecrawler.FieldEntityType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entity_type", values[i])
			} else if value.Valid {
				scc.EntityType = statscachecrawler.EntityType(value.String)
			}
		case statscachecrawler.FieldEntityID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entity_id", values[i])
			} else if value.Valid {
				scc.EntityID = value.String
			}
		case statscachecrawler.FieldVisitorKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field visitor_kind", values[i])
			} else if value.Valid {
				scc.VisitorKind = statscachecrawler.VisitorKind(value.String)
			}
		case statscachecrawler.FieldCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field count", values[i])
			} else if value.Valid {
				scc.Count = int(value.Int64)
			}
		case statscachecrawler.FieldSyncedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field synced_at", values[i])
			} else if value.Valid {
				scc.SyncedAt = value.Time
			}
		default:
			scc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the StatsCacheCrawler.
// This includes values selected through modifiers, order, etc.
func (scc *StatsCacheCrawler) Value(name string) (ent.Value, error) {
	return scc.selectValues.Get(name)
}

// Update returns a builder for updating this StatsCacheCrawler.
// Note that you need to call StatsCacheCrawler.Unwrap() before calling this method if this StatsCacheCrawler
// was returned from a transaction, and the transaction was committed or rolled back.
func (scc *StatsCacheCrawler) Update() *StatsCacheCrawlerUpdateOne {
	return NewStatsCacheCrawlerClient(scc.config).UpdateOne(scc)
}

// Unwrap unwraps the StatsCacheCrawler entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (scc *StatsCacheCrawler) Unwrap() *StatsCacheCrawler {
	_tx, ok := scc.config.driver.(*txDriver)
	if !ok {
		panic("ent: StatsCacheCrawler is not a transactional entity")
	}
	scc.config.driver = _tx.drv
	return scc
}

// String implements the fmt.Stringer.
func (scc *StatsCacheCrawler) String() string {
	var builder strings.Builder
	builder.WriteString("StatsCacheCrawler(")
	builder.WriteString(fmt.Sprintf("id=%v, ", scc.ID))
	builder.WriteString("entity_type=")
	builder.WriteString(fmt.Sprintf("%v", scc.EntityType))
	builder.WriteString(", ")
	builder.WriteString("entity_id=")
	builder.WriteString(scc.EntityID)
	builder.WriteString(", ")
	builder.WriteString("visitor_kind=")
	builder.WriteString(fmt.Sprintf("%v", scc.VisitorKind))
	builder.WriteString(", ")
	builder.WriteString("count=")
	builder.WriteString(fmt.Sprintf("%v", scc.Count))
	builder.WriteString(", ")
	builder.WriteString("synced_at=")
	builder.WriteString(scc.SyncedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// StatsCacheCrawlers is a parsable slice of StatsCacheCrawler.
type StatsCacheCrawlers []*StatsCacheCrawler
