// Code generated by ent, DO NOT EDIT.

package statscachecrawler

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the statscachecrawler type in the database.
	Label = "stats_cache_crawler"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEntityType holds the string denoting the entity_type field in the database.
	FieldEntityType = "entity_type"
	// FieldEntityID holds the string denoting the entity_id field in the database.
	FieldEntityID = "entity_id"
	// FieldVisitorKind holds the string denoting the visitor_kind field in the database.
	FieldVisitorKind = "visitor_kind"
	// FieldCount holds the string denoting the count field in the database.
	FieldCount = "count"
	// FieldSyncedAt holds the string denoting the synced_at field in the database.
	FieldSyncedAt = "synced_at"
	// Table holds the table name of the statscachecrawler in the database.
	Table = "stats_cache_crawler"
)

// Columns holds all SQL columns for statscachecrawler fields.
var Columns = []string{
	FieldID,
	FieldEntityType,
	FieldEntityID,
	FieldVisitorKind,
	FieldCount,
	FieldSyncedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCount holds the default value on creation for the "count" field.
	DefaultCount int
	// DefaultSyncedAt holds the default value on creation for the "synced_at" field.
	DefaultSyncedAt func() time.Time
)

// EntityType defines the type for the "entity_type" enum field.
type EntityType string

// EntityType values.
const (
	EntityTypeBlog    EntityType = "blog"
	EntityTypeProject EntityType = "project"
	EntityTypeIdea    EntityType = "idea"
	EntityTypeEpisode EntityType = "episode"
	EntityTypeResume  EntityType = "resume"
	EntityTypeMoment  EntityType = "moment"
)

func (et EntityType) String() string {
	return string(et)
}

// EntityTypeValidator is a validator for the "entity_type" field enum values. It is called by the builders before save.
func EntityTypeValidator(et EntityType) error {
	switch et {
	case EntityTypeBlog, EntityTypeProject, EntityTypeIdea, EntityTypeEpisode, EntityTypeResume, EntityTypeMoment:
		return nil
	default:
		return fmt.Errorf("statscachecrawler: invalid enum value for entity_type field: %q", et)
	}
}

// VisitorKind defines the type for the "visitor_kind" enum field.
type VisitorKind string

// VisitorKind values.
const (
	VisitorKindHuman     VisitorKind = "human"
	VisitorKindSearchBot VisitorKind = "search_bot"
	VisitorKindAiBot     VisitorKind = "ai_bot"
	VisitorKindUnknown   VisitorKind = "unknown"
)

func (vk VisitorKind) String() string {
	return string(vk)
}

// VisitorKindValidator is a validator for the "visitor_kind" field enum values. It is called by the builders before save.
func VisitorKindValidator(vk VisitorKind) error {
	switch vk {
	case VisitorKindHuman, VisitorKindSearchBot, VisitorKindAiBot, VisitorKindUnknown:
		return nil
	default:
		return fmt.Errorf("statscachecrawler: invalid enum value for visitor_kind field: %q", vk)
	}
}

// OrderOption defines the ordering options for the StatsCacheCrawler queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEntityType orders the results by the entity_type field.
func ByEntityType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntityType, opts...).ToFunc()
}

// ByEntityID orders the results by the entity_id field.
func ByEntityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntityID, opts...).ToFunc()
}

// ByVisitorKind orders the results by the visitor_kind field.
func ByVisitorKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVisitorKind, opts...).ToFunc()
}

// ByCount orders the results by the count field.
func ByCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCount, opts...).ToFunc()
}

// BySyncedAt orders the results by the synced_at field.
func BySyncedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncedAt, opts...).ToFunc()
}
