// Code generated by ent, DO NOT EDIT.

package statscachecrawler

import (
	"silan-backend/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldLTE(FieldID, id))
}

// EntityID applies equality check predicate on the "entity_id" field. It's identical to EntityIDEQ.
func EntityID(v string) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldEQ(FieldEntityID, v))
}

// Count applies equality check predicate on the "count" field. It's identical to CountEQ.
func Count(v int) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldEQ(FieldCount, v))
}

// SyncedAt applies equality check predicate on the "synced_at" field. It's identical to SyncedAtEQ.
func SyncedAt(v time.Time) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldEQ(FieldSyncedAt, v))
}

// EntityTypeEQ applies the EQ predicate on the "entity_type" field.
func EntityTypeEQ(v EntityType) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldEQ(FieldEntityType, v))
}

// EntityTypeNEQ applies the NEQ predicate on the "entity_type" field.
func EntityTypeNEQ(v EntityType) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldNEQ(FieldEntityType, v))
}

// EntityTypeIn applies the In predicate on the "entity_type" field.
func EntityTypeIn(vs ...EntityType) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldIn(FieldEntityType, vs...))
}

// EntityTypeNotIn applies the NotIn predicate on the "entity_type" field.
func EntityTypeNotIn(vs ...EntityType) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldNotIn(FieldEntityType, vs...))
}

// EntityIDEQ applies the EQ predicate on the "entity_id" field.
func EntityIDEQ(v string) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldEQ(FieldEntityID, v))
}

// EntityIDNEQ applies the NEQ predicate on the "entity_id" field.
func EntityIDNEQ(v string) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldNEQ(FieldEntityID, v))
}

// EntityIDIn applies the In predicate on the "entity_id" field.
func EntityIDIn(vs ...string) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldIn(FieldEntityID, vs...))
}

// EntityIDNotIn applies the NotIn predicate on the "entity_id" field.
func EntityIDNotIn(vs ...string) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldNotIn(FieldEntityID, vs...))
}

// EntityIDGT applies the GT predicate on the "entity_id" field.
func EntityIDGT(v string) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldGT(FieldEntityID, v))
}

// EntityIDGTE applies the GTE predicate on the "entity_id" field.
func EntityIDGTE(v string) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldGTE(FieldEntityID, v))
}

// EntityIDLT applies the LT predicate on the "entity_id" field.
func EntityIDLT(v string) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldLT(FieldEntityID, v))
}

// EntityIDLTE applies the LTE predicate on the "entity_id" field.
func EntityIDLTE(v string) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldLTE(FieldEntityID, v))
}

// EntityIDContains applies the Contains predicate on the "entity_id" field.
func EntityIDContains(v string) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldContains(FieldEntityID, v))
}

// EntityIDHasPrefix applies the HasPrefix predicate on the "entity_id" field.
func EntityIDHasPrefix(v string) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldHasPrefix(FieldEntityID, v))
}

// EntityIDHasSuffix applies the HasSuffix predicate on the "entity_id" field.
func EntityIDHasSuffix(v string) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldHasSuffix(FieldEntityID, v))
}

// EntityIDEqualFold applies the EqualFold predicate on the "entity_id" field.
func EntityIDEqualFold(v string) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldEqualFold(FieldEntityID, v))
}

// EntityIDContainsFold applies the ContainsFold predicate on the "entity_id" field.
func EntityIDContainsFold(v string) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldContainsFold(FieldEntityID, v))
}

// VisitorKindEQ applies the EQ predicate on the "visitor_kind" field.
func VisitorKindEQ(v VisitorKind) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldEQ(FieldVisitorKind, v))
}

// VisitorKindNEQ applies the NEQ predicate on the "visitor_kind" field.
func VisitorKindNEQ(v VisitorKind) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldNEQ(FieldVisitorKind, v))
}

// VisitorKindIn applies the In predicate on the "visitor_kind" field.
func VisitorKindIn(vs ...VisitorKind) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldIn(FieldVisitorKind, vs...))
}

// VisitorKindNotIn applies the NotIn predicate on the "visitor_kind" field.
func VisitorKindNotIn(vs ...VisitorKind) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldNotIn(FieldVisitorKind, vs...))
}

// CountEQ applies the EQ predicate on the "count" field.
func CountEQ(v int) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldEQ(FieldCount, v))
}

// CountNEQ applies the NEQ predicate on the "count" field.
func CountNEQ(v int) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldNEQ(FieldCount, v))
}

// CountIn applies the In predicate on the "count" field.
func CountIn(vs ...int) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldIn(FieldCount, vs...))
}

// CountNotIn applies the NotIn predicate on the "count" field.
func CountNotIn(vs ...int) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldNotIn(FieldCount, vs...))
}

// CountGT applies the GT predicate on the "count" field.
func CountGT(v int) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldGT(FieldCount, v))
}

// CountGTE applies the GTE predicate on the "count" field.
func CountGTE(v int) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldGTE(FieldCount, v))
}

// CountLT applies the LT predicate on the "count" field.
func CountLT(v int) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldLT(FieldCount, v))
}

// CountLTE applies the LTE predicate on the "count" field.
func CountLTE(v int) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldLTE(FieldCount, v))
}

// SyncedAtEQ applies the EQ predicate on the "synced_at" field.
func SyncedAtEQ(v time.Time) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldEQ(FieldSyncedAt, v))
}

// SyncedAtNEQ applies the NEQ predicate on the "synced_at" field.
func SyncedAtNEQ(v time.Time) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldNEQ(FieldSyncedAt, v))
}

// SyncedAtIn applies the In predicate on the "synced_at" field.
func SyncedAtIn(vs ...time.Time) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldIn(FieldSyncedAt, vs...))
}

// SyncedAtNotIn applies the NotIn predicate on the "synced_at" field.
func SyncedAtNotIn(vs ...time.Time) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldNotIn(FieldSyncedAt, vs...))
}

// SyncedAtGT applies the GT predicate on the "synced_at" field.
func SyncedAtGT(v time.Time) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldGT(FieldSyncedAt, v))
}

// SyncedAtGTE applies the GTE predicate on the "synced_at" field.
func SyncedAtGTE(v time.Time) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldGTE(FieldSyncedAt, v))
}

// SyncedAtLT applies the LT predicate on the "synced_at" field.
func SyncedAtLT(v time.Time) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldLT(FieldSyncedAt, v))
}

// SyncedAtLTE applies the LTE predicate on the "synced_at" field.
func SyncedAtLTE(v time.Time) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.FieldLTE(FieldSyncedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StatsCacheCrawler) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StatsCacheCrawler) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StatsCacheCrawler) predicate.StatsCacheCrawler {
	return predicate.StatsCacheCrawler(sql.NotPredicates(p))
}
