// Code generated by ent, DO NOT EDIT.

package statscachevisitor

import (
	"silan-backend/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldLTE(FieldID, id))
}

// EntityID applies equality check predicate on the "entity_id" field. It's identical to EntityIDEQ.
func EntityID(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldEQ(FieldEntityID, v))
}

// Fingerprint applies equality check predicate on the "fingerprint" field. It's identical to FingerprintEQ.
func Fingerprint(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldEQ(FieldFingerprint, v))
}

// IPMasked applies equality check predicate on the "ip_masked" field. It's identical to IPMaskedEQ.
func IPMasked(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldEQ(FieldIPMasked, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldEQ(FieldLastSeenAt, v))
}

// SyncedAt applies equality check predicate on the "synced_at" field. It's identical to SyncedAtEQ.
func SyncedAt(v time.Time) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldEQ(FieldSyncedAt, v))
}

// EntityTypeEQ applies the EQ predicate on the "entity_type" field.
func EntityTypeEQ(v EntityType) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldEQ(FieldEntityType, v))
}

// EntityTypeNEQ applies the NEQ predicate on the "entity_type" field.
func EntityTypeNEQ(v EntityType) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldNEQ(FieldEntityType, v))
}

// EntityTypeIn applies the In predicate on the "entity_type" field.
func EntityTypeIn(vs ...EntityType) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldIn(FieldEntityType, vs...))
}

// EntityTypeNotIn applies the NotIn predicate on the "entity_type" field.
func EntityTypeNotIn(vs ...EntityType) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldNotIn(FieldEntityType, vs...))
}

// EntityIDEQ applies the EQ predicate on the "entity_id" field.
func EntityIDEQ(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldEQ(FieldEntityID, v))
}

// EntityIDNEQ applies the NEQ predicate on the "entity_id" field.
func EntityIDNEQ(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldNEQ(FieldEntityID, v))
}

// EntityIDIn applies the In predicate on the "entity_id" field.
func EntityIDIn(vs ...string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldIn(FieldEntityID, vs...))
}

// EntityIDNotIn applies the NotIn predicate on the "entity_id" field.
func EntityIDNotIn(vs ...string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldNotIn(FieldEntityID, vs...))
}

// EntityIDGT applies the GT predicate on the "entity_id" field.
func EntityIDGT(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldGT(FieldEntityID, v))
}

// EntityIDGTE applies the GTE predicate on the "entity_id" field.
func EntityIDGTE(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldGTE(FieldEntityID, v))
}

// EntityIDLT applies the LT predicate on the "entity_id" field.
func EntityIDLT(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldLT(FieldEntityID, v))
}

// EntityIDLTE applies the LTE predicate on the "entity_id" field.
func EntityIDLTE(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldLTE(FieldEntityID, v))
}

// EntityIDContains applies the Contains predicate on the "entity_id" field.
func EntityIDContains(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldContains(FieldEntityID, v))
}

// EntityIDHasPrefix applies the HasPrefix predicate on the "entity_id" field.
func EntityIDHasPrefix(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldHasPrefix(FieldEntityID, v))
}

// EntityIDHasSuffix applies the HasSuffix predicate on the "entity_id" field.
func EntityIDHasSuffix(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldHasSuffix(FieldEntityID, v))
}

// EntityIDEqualFold applies the EqualFold predicate on the "entity_id" field.
func EntityIDEqualFold(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldEqualFold(FieldEntityID, v))
}

// EntityIDContainsFold applies the ContainsFold predicate on the "entity_id" field.
func EntityIDContainsFold(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldContainsFold(FieldEntityID, v))
}

// FingerprintEQ applies the EQ predicate on the "fingerprint" field.
func FingerprintEQ(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldEQ(FieldFingerprint, v))
}

// FingerprintNEQ applies the NEQ predicate on the "fingerprint" field.
func FingerprintNEQ(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldNEQ(FieldFingerprint, v))
}

// FingerprintIn applies the In predicate on the "fingerprint" field.
func FingerprintIn(vs ...string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldIn(FieldFingerprint, vs...))
}

// FingerprintNotIn applies the NotIn predicate on the "fingerprint" field.
func FingerprintNotIn(vs ...string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldNotIn(FieldFingerprint, vs...))
}

// FingerprintGT applies the GT predicate on the "fingerprint" field.
func FingerprintGT(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldGT(FieldFingerprint, v))
}

// FingerprintGTE applies the GTE predicate on the "fingerprint" field.
func FingerprintGTE(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldGTE(FieldFingerprint, v))
}

// FingerprintLT applies the LT predicate on the "fingerprint" field.
func FingerprintLT(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldLT(FieldFingerprint, v))
}

// FingerprintLTE applies the LTE predicate on the "fingerprint" field.
func FingerprintLTE(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldLTE(FieldFingerprint, v))
}

// FingerprintContains applies the Contains predicate on the "fingerprint" field.
func FingerprintContains(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldContains(FieldFingerprint, v))
}

// FingerprintHasPrefix applies the HasPrefix predicate on the "fingerprint" field.
func FingerprintHasPrefix(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldHasPrefix(FieldFingerprint, v))
}

// FingerprintHasSuffix applies the HasSuffix predicate on the "fingerprint" field.
func FingerprintHasSuffix(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldHasSuffix(FieldFingerprint, v))
}

// FingerprintEqualFold applies the EqualFold predicate on the "fingerprint" field.
func FingerprintEqualFold(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldEqualFold(FieldFingerprint, v))
}

// FingerprintContainsFold applies the ContainsFold predicate on the "fingerprint" field.
func FingerprintContainsFold(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldContainsFold(FieldFingerprint, v))
}

// IPMaskedEQ applies the EQ predicate on the "ip_masked" field.
func IPMaskedEQ(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldEQ(FieldIPMasked, v))
}

// IPMaskedNEQ applies the NEQ predicate on the "ip_masked" field.
func IPMaskedNEQ(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldNEQ(FieldIPMasked, v))
}

// IPMaskedIn applies the In predicate on the "ip_masked" field.
func IPMaskedIn(vs ...string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldIn(FieldIPMasked, vs...))
}

// IPMaskedNotIn applies the NotIn predicate on the "ip_masked" field.
func IPMaskedNotIn(vs ...string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldNotIn(FieldIPMasked, vs...))
}

// IPMaskedGT applies the GT predicate on the "ip_masked" field.
func IPMaskedGT(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldGT(FieldIPMasked, v))
}

// IPMaskedGTE applies the GTE predicate on the "ip_masked" field.
func IPMaskedGTE(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldGTE(FieldIPMasked, v))
}

// IPMaskedLT applies the LT predicate on the "ip_masked" field.
func IPMaskedLT(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldLT(FieldIPMasked, v))
}

// IPMaskedLTE applies the LTE predicate on the "ip_masked" field.
func IPMaskedLTE(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldLTE(FieldIPMasked, v))
}

// IPMaskedContains applies the Contains predicate on the "ip_masked" field.
func IPMaskedContains(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldContains(FieldIPMasked, v))
}

// IPMaskedHasPrefix applies the HasPrefix predicate on the "ip_masked" field.
func IPMaskedHasPrefix(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldHasPrefix(FieldIPMasked, v))
}

// IPMaskedHasSuffix applies the HasSuffix predicate on the "ip_masked" field.
func IPMaskedHasSuffix(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldHasSuffix(FieldIPMasked, v))
}

// IPMaskedEqualFold applies the EqualFold predicate on the "ip_masked" field.
func IPMaskedEqualFold(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldEqualFold(FieldIPMasked, v))
}

// IPMaskedContainsFold applies the ContainsFold predicate on the "ip_masked" field.
func IPMaskedContainsFold(v string) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldContainsFold(FieldIPMasked, v))
}

// VisitorKindEQ applies the EQ predicate on the "visitor_kind" field.
func VisitorKindEQ(v VisitorKind) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldEQ(FieldVisitorKind, v))
}

// VisitorKindNEQ applies the NEQ predicate on the "visitor_kind" field.
func VisitorKindNEQ(v VisitorKind) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldNEQ(FieldVisitorKind, v))
}

// VisitorKindIn applies the In predicate on the "visitor_kind" field.
func VisitorKindIn(vs ...VisitorKind) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldIn(FieldVisitorKind, vs...))
}

// VisitorKindNotIn applies the NotIn predicate on the "visitor_kind" field.
func VisitorKindNotIn(vs ...VisitorKind) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldNotIn(FieldVisitorKind, vs...))
}

// ReferrerKindEQ applies the EQ predicate on the "referrer_kind" field.
func ReferrerKindEQ(v ReferrerKind) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldEQ(FieldReferrerKind, v))
}

// ReferrerKindNEQ applies the NEQ predicate on the "referrer_kind" field.
func ReferrerKindNEQ(v ReferrerKind) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldNEQ(FieldReferrerKind, v))
}

// ReferrerKindIn applies the In predicate on the "referrer_kind" field.
func ReferrerKindIn(vs ...ReferrerKind) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldIn(FieldReferrerKind, vs...))
}

// ReferrerKindNotIn applies the NotIn predicate on the "referrer_kind" field.
func ReferrerKindNotIn(vs ...ReferrerKind) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldNotIn(FieldReferrerKind, vs...))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldLTE(FieldLastSeenAt, v))
}

// SyncedAtEQ applies the EQ predicate on the "synced_at" field.
func SyncedAtEQ(v time.Time) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldEQ(FieldSyncedAt, v))
}

// SyncedAtNEQ applies the NEQ predicate on the "synced_at" field.
func SyncedAtNEQ(v time.Time) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldNEQ(FieldSyncedAt, v))
}

// SyncedAtIn applies the In predicate on the "synced_at" field.
func SyncedAtIn(vs ...time.Time) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldIn(FieldSyncedAt, vs...))
}

// SyncedAtNotIn applies the NotIn predicate on the "synced_at" field.
func SyncedAtNotIn(vs ...time.Time) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldNotIn(FieldSyncedAt, vs...))
}

// SyncedAtGT applies the GT predicate on the "synced_at" field.
func SyncedAtGT(v time.Time) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldGT(FieldSyncedAt, v))
}

// SyncedAtGTE applies the GTE predicate on the "synced_at" field.
func SyncedAtGTE(v time.Time) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldGTE(FieldSyncedAt, v))
}

// SyncedAtLT applies the LT predicate on the "synced_at" field.
func SyncedAtLT(v time.Time) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldLT(FieldSyncedAt, v))
}

// SyncedAtLTE applies the LTE predicate on the "synced_at" field.
func SyncedAtLTE(v time.Time) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.FieldLTE(FieldSyncedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StatsCacheVisitor) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StatsCacheVisitor) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StatsCacheVisitor) predicate.StatsCacheVisitor {
	return predicate.StatsCacheVisitor(sql.NotPredicates(p))
}
