// Code generated by ent, DO NOT EDIT.

package commentlike

import (
	"silan-backend/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldLTE(FieldID, id))
}

// CommentID applies equality check predicate on the "comment_id" field. It's identical to CommentIDEQ.
func CommentID(v uuid.UUID) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldEQ(FieldCommentID, v))
}

// UserIdentityID applies equality check predicate on the "user_identity_id" field. It's identical to UserIdentityIDEQ.
func UserIdentityID(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldEQ(FieldUserIdentityID, v))
}

// Fingerprint applies equality check predicate on the "fingerprint" field. It's identical to FingerprintEQ.
func Fingerprint(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldEQ(FieldFingerprint, v))
}

// IPAddress applies equality check predicate on the "ip_address" field. It's identical to IPAddressEQ.
func IPAddress(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldEQ(FieldIPAddress, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldEQ(FieldCreatedAt, v))
}

// CommentIDEQ applies the EQ predicate on the "comment_id" field.
func CommentIDEQ(v uuid.UUID) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldEQ(FieldCommentID, v))
}

// CommentIDNEQ applies the NEQ predicate on the "comment_id" field.
func CommentIDNEQ(v uuid.UUID) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldNEQ(FieldCommentID, v))
}

// CommentIDIn applies the In predicate on the "comment_id" field.
func CommentIDIn(vs ...uuid.UUID) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldIn(FieldCommentID, vs...))
}

// CommentIDNotIn applies the NotIn predicate on the "comment_id" field.
func CommentIDNotIn(vs ...uuid.UUID) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldNotIn(FieldCommentID, vs...))
}

// UserIdentityIDEQ applies the EQ predicate on the "user_identity_id" field.
func UserIdentityIDEQ(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldEQ(FieldUserIdentityID, v))
}

// UserIdentityIDNEQ applies the NEQ predicate on the "user_identity_id" field.
func UserIdentityIDNEQ(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldNEQ(FieldUserIdentityID, v))
}

// UserIdentityIDIn applies the In predicate on the "user_identity_id" field.
func UserIdentityIDIn(vs ...string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldIn(FieldUserIdentityID, vs...))
}

// UserIdentityIDNotIn applies the NotIn predicate on the "user_identity_id" field.
func UserIdentityIDNotIn(vs ...string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldNotIn(FieldUserIdentityID, vs...))
}

// UserIdentityIDGT applies the GT predicate on the "user_identity_id" field.
func UserIdentityIDGT(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldGT(FieldUserIdentityID, v))
}

// UserIdentityIDGTE applies the GTE predicate on the "user_identity_id" field.
func UserIdentityIDGTE(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldGTE(FieldUserIdentityID, v))
}

// UserIdentityIDLT applies the LT predicate on the "user_identity_id" field.
func UserIdentityIDLT(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldLT(FieldUserIdentityID, v))
}

// UserIdentityIDLTE applies the LTE predicate on the "user_identity_id" field.
func UserIdentityIDLTE(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldLTE(FieldUserIdentityID, v))
}

// UserIdentityIDContains applies the Contains predicate on the "user_identity_id" field.
func UserIdentityIDContains(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldContains(FieldUserIdentityID, v))
}

// UserIdentityIDHasPrefix applies the HasPrefix predicate on the "user_identity_id" field.
func UserIdentityIDHasPrefix(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldHasPrefix(FieldUserIdentityID, v))
}

// UserIdentityIDHasSuffix applies the HasSuffix predicate on the "user_identity_id" field.
func UserIdentityIDHasSuffix(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldHasSuffix(FieldUserIdentityID, v))
}

// UserIdentityIDIsNil applies the IsNil predicate on the "user_identity_id" field.
func UserIdentityIDIsNil() predicate.CommentLike {
	return predicate.CommentLike(sql.FieldIsNull(FieldUserIdentityID))
}

// UserIdentityIDNotNil applies the NotNil predicate on the "user_identity_id" field.
func UserIdentityIDNotNil() predicate.CommentLike {
	return predicate.CommentLike(sql.FieldNotNull(FieldUserIdentityID))
}

// UserIdentityIDEqualFold applies the EqualFold predicate on the "user_identity_id" field.
func UserIdentityIDEqualFold(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldEqualFold(FieldUserIdentityID, v))
}

// UserIdentityIDContainsFold applies the ContainsFold predicate on the "user_identity_id" field.
func UserIdentityIDContainsFold(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldContainsFold(FieldUserIdentityID, v))
}

// FingerprintEQ applies the EQ predicate on the "fingerprint" field.
func FingerprintEQ(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldEQ(FieldFingerprint, v))
}

// FingerprintNEQ applies the NEQ predicate on the "fingerprint" field.
func FingerprintNEQ(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldNEQ(FieldFingerprint, v))
}

// FingerprintIn applies the In predicate on the "fingerprint" field.
func FingerprintIn(vs ...string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldIn(FieldFingerprint, vs...))
}

// FingerprintNotIn applies the NotIn predicate on the "fingerprint" field.
func FingerprintNotIn(vs ...string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldNotIn(FieldFingerprint, vs...))
}

// FingerprintGT applies the GT predicate on the "fingerprint" field.
func FingerprintGT(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldGT(FieldFingerprint, v))
}

// FingerprintGTE applies the GTE predicate on the "fingerprint" field.
func FingerprintGTE(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldGTE(FieldFingerprint, v))
}

// FingerprintLT applies the LT predicate on the "fingerprint" field.
func FingerprintLT(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldLT(FieldFingerprint, v))
}

// FingerprintLTE applies the LTE predicate on the "fingerprint" field.
func FingerprintLTE(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldLTE(FieldFingerprint, v))
}

// FingerprintContains applies the Contains predicate on the "fingerprint" field.
func FingerprintContains(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldContains(FieldFingerprint, v))
}

// FingerprintHasPrefix applies the HasPrefix predicate on the "fingerprint" field.
func FingerprintHasPrefix(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldHasPrefix(FieldFingerprint, v))
}

// FingerprintHasSuffix applies the HasSuffix predicate on the "fingerprint" field.
func FingerprintHasSuffix(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldHasSuffix(FieldFingerprint, v))
}

// FingerprintIsNil applies the IsNil predicate on the "fingerprint" field.
func FingerprintIsNil() predicate.CommentLike {
	return predicate.CommentLike(sql.FieldIsNull(FieldFingerprint))
}

// FingerprintNotNil applies the NotNil predicate on the "fingerprint" field.
func FingerprintNotNil() predicate.CommentLike {
	return predicate.CommentLike(sql.FieldNotNull(FieldFingerprint))
}

// FingerprintEqualFold applies the EqualFold predicate on the "fingerprint" field.
func FingerprintEqualFold(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldEqualFold(FieldFingerprint, v))
}

// FingerprintContainsFold applies the ContainsFold predicate on the "fingerprint" field.
func FingerprintContainsFold(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldContainsFold(FieldFingerprint, v))
}

// IPAddressEQ applies the EQ predicate on the "ip_address" field.
func IPAddressEQ(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldEQ(FieldIPAddress, v))
}

// IPAddressNEQ applies the NEQ predicate on the "ip_address" field.
func IPAddressNEQ(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldNEQ(FieldIPAddress, v))
}

// IPAddressIn applies the In predicate on the "ip_address" field.
func IPAddressIn(vs ...string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldIn(FieldIPAddress, vs...))
}

// IPAddressNotIn applies the NotIn predicate on the "ip_address" field.
func IPAddressNotIn(vs ...string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldNotIn(FieldIPAddress, vs...))
}

// IPAddressGT applies the GT predicate on the "ip_address" field.
func IPAddressGT(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldGT(FieldIPAddress, v))
}

// IPAddressGTE applies the GTE predicate on the "ip_address" field.
func IPAddressGTE(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldGTE(FieldIPAddress, v))
}

// IPAddressLT applies the LT predicate on the "ip_address" field.
func IPAddressLT(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldLT(FieldIPAddress, v))
}

// IPAddressLTE applies the LTE predicate on the "ip_address" field.
func IPAddressLTE(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldLTE(FieldIPAddress, v))
}

// IPAddressContains applies the Contains predicate on the "ip_address" field.
func IPAddressContains(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldContains(FieldIPAddress, v))
}

// IPAddressHasPrefix applies the HasPrefix predicate on the "ip_address" field.
func IPAddressHasPrefix(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldHasPrefix(FieldIPAddress, v))
}

// IPAddressHasSuffix applies the HasSuffix predicate on the "ip_address" field.
func IPAddressHasSuffix(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldHasSuffix(FieldIPAddress, v))
}

// IPAddressIsNil applies the IsNil predicate on the "ip_address" field.
func IPAddressIsNil() predicate.CommentLike {
	return predicate.CommentLike(sql.FieldIsNull(FieldIPAddress))
}

// IPAddressNotNil applies the NotNil predicate on the "ip_address" field.
func IPAddressNotNil() predicate.CommentLike {
	return predicate.CommentLike(sql.FieldNotNull(FieldIPAddress))
}

// IPAddressEqualFold applies the EqualFold predicate on the "ip_address" field.
func IPAddressEqualFold(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldEqualFold(FieldIPAddress, v))
}

// IPAddressContainsFold applies the ContainsFold predicate on the "ip_address" field.
func IPAddressContainsFold(v string) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldContainsFold(FieldIPAddress, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CommentLike {
	return predicate.CommentLike(sql.FieldLTE(FieldCreatedAt, v))
}

// HasComment applies the HasEdge predicate on the "comment" edge.
func HasComment() predicate.CommentLike {
	return predicate.CommentLike(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CommentTable, CommentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCommentWith applies the HasEdge predicate on the "comment" edge with a given conditions (other predicates).
func HasCommentWith(preds ...predicate.BlogComment) predicate.CommentLike {
	return predicate.CommentLike(func(s *sql.Selector) {
		step := newCommentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUserIdentity applies the HasEdge predicate on the "user_identity" edge.
func HasUserIdentity() predicate.CommentLike {
	return predicate.CommentLike(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserIdentityTable, UserIdentityColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserIdentityWith applies the HasEdge predicate on the "user_identity" edge with a given conditions (other predicates).
func HasUserIdentityWith(preds ...predicate.UserIdentity) predicate.CommentLike {
	return predicate.CommentLike(func(s *sql.Selector) {
		step := newUserIdentityStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CommentLike) predicate.CommentLike {
	return predicate.CommentLike(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CommentLike) predicate.CommentLike {
	return predicate.CommentLike(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CommentLike) predicate.CommentLike {
	return predicate.CommentLike(sql.NotPredicates(p))
}
